<?php

/**
 * Implements hook_block_info().
 */
function asu_alert_banner_block_info() {
  $blocks = array();
  $blocks['asu_alert_banner'] = array(
    'info' => t('ASU Alert Banner'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function asu_alert_banner_block_configure($delta='') {
  $form = array();
  
  switch($delta) 
  {
    case 'asu_alert_banner' :
      // Override Block title for user friendliness
      $form['title'] = array(
        '#type' => 'hidden',
        '#description' => t( "How much money are you asking for?" ),
        '#default_value' => t('')
      );
      // Text field form element
      $form['banner_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Banner Title'),
        '#default_value' => variable_get('banner_title', ''),
      );
      // WYSIWYG form element
      $form['banner_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Banner body'),
        '#default_value' => variable_get('banner_body', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function asu_alert_banner_block_save($delta = '', $edit = array()) 
{
  switch($delta) 
  {
    case 'asu_alert_banner':
      // Saving the title and WYISWYG fields as variables     
      variable_set('banner_title', $edit['banner_title']);
      variable_set('banner_body', $edit['banner_body']['value']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function asu_alert_banner_block_view($delta='') 
{
  $block = array();
  
  switch($delta) 
  {
    case 'asu_alert_banner' :
      $block['subject'] = NULL;
      $block['content'] = asu_alert_banner_block_render();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_view_alter()
 */
function block_example_block_view_alter(&$data, $block) 
{
  // Checks if block title is not empty
  if (!empty($block->title)) 
  {
    // Sets title to NULL.
    $data['subject'] = NULL;
  }
}
 
/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return returns a renderable array of block content.
 */
function asu_alert_banner_block_render() 
{
  $block = array();
 
  // Capture WYSIWYG text from the variable
  $title = variable_get('banner_title', '');
  $text = variable_get('banner_body', '');
 
  // Block output in HTML with div wrapper
  $block = array(
    'text' => array(
      '#prefix' => '', 
      '#type' => 'markup', 
      '#markup' => asu_alert_banner_markup($title, $text),
      '#attached' => array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => drupal_get_path('module', 'asu_alert_banner') . '/css/styles.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => drupal_get_path('module', 'asu_alert_banner') , '/js/script.js',
          )
        )
      ), 
    ),
  );

  return $block; 
}

/**
 * Auxillary function that returns pre-set markup
 */
function asu_alert_banner_markup($title, $text)
{
  return '<div class="alertbody">
  <div class="alertcontainer">
    <div class="alerticon"><i aria-hidden="true" class="fa fa-exclamation-circle">&zwnj;</i></div>
    <div class="alertbody">
      <h2>' . $title . '</h2><div>' . $text . 
    '</div></div>
    </div>
  </div>';
}