<?php

include_once('panopoly_core.features.inc');
include_once('panopoly_core.defaultconfig.inc');

/**
 * Implementation of hook_init()
 */
function panopoly_core_init() {

  // Override the Chaos Tools Modal Default Settings
  $default_style = array(
    'CToolsModal' => array(
      'modalSize' => array(
        'type' => 'scale',
        'width' => '.9',
        'height' => '.9',
        'addWidth' => 0,
        'addHeight' => 0,
        'contentRight' => 25,
        'contentBottom' => 75,
      ),
      'modalOptions' => array(
        'opacity' => '.55',
        'background-color' => '#FFF',
      ),
      'animationSpeed' => 'fast',
      'modalTheme' => 'CToolsModalDialog',
      'throbberTheme' => 'CToolsModalThrobber',
    ),
  );
  drupal_add_js($default_style, 'setting');

  // Set the current page title in the breadcrumb
  if (variable_get('panopoly_core_breadcrumb_title', TRUE)) {
    $breadcrumb = drupal_get_breadcrumb();
    if (count($breadcrumb) && drupal_get_title()) {
      $breadcrumb[] = drupal_get_title();

      // If it is the homepage, remove the breadcrumb
      if (drupal_is_front_page()) {
        $breadcrumb = array();
      }
      drupal_set_breadcrumb($breadcrumb);
    }
  }
}

/**
 * Implements hook_apps_app_info()
 */
function panopoly_core_apps_app_info() {
  return array(
    'configure form' => 'panopoly_core_configure_form',
  );
}

/**
 * Configuration Form for Panopoly Core
 */
function panopoly_core_configure_form($form, &$form_state) {
  $form = array();

  $form['panopoly_core_breadcrumb_title'] = array(
    '#title' => t('Append Page Title to Site Breadcrumb'),
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => array(
      '1' => 'Enabled',
      '0' => 'Disabled',
    ),
    '#default_value' => variable_get('panopoly_core_breadcrumb_title', 1),
    '#description' => t('Do you want Panopoly to append the page title to the site breadcrumb?'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_preprocess_html()
 *
 * We are telling the site that everything is a region-content. This is important since
 * when we disable the block module it loses this classes which some things assume for generalized
 * CSS considerations (i.e. Bartik's spacing of ul/ol).
 */
function panopoly_core_preprocess_html(&$variables) {
  $variables['classes_array'][] = 'region-content';
}

/**
 * Implements hook_apps_servers_info()
 */
function panopoly_core_apps_servers_info() {
  $info =  drupal_parse_info_file(drupal_get_path('module', 'panopoly_core') . '/panopoly_core.info');
  return array(
    'panopoly' => array(
      'title' => 'Panopoly',
      'description' => 'Apps for Panopoly',
      'manifest' => (empty($info['version']) || $info['version'] == '7.x-1.x-dev' || strpos($info['version'], '-dev')) ? 'http://apps.getpantheon.com/panopoly-dev' : 'http://apps.getpantheon.com/panopoly',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 *
 * This hook is implemented to address an issue with core that can be 
 * seen here - http://drupal.org/node/1400256. There is a patch that helps
 * to resolve this issue, but it (a) has performance issues and (b) why
 * patch/hack core when you can do crazy workarounds in contrib. 
 */
function panopoly_core_entity_info_alter(&$entity_info) {
  if (variable_get('install_task', 'done') != 'done') {
    _field_info_collate_fields();
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * This hook is implemented to move our panopoly_core_entity_info_alter()
 * hook implementation to the bottom of the ordering so as to run after the
 * problematic entity_entity_info_alter() implementation. 
 */
function panopoly_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_info_alter' || $hook == 'css_alter') {
    $group = $implementations['panopoly_core'];
    unset($implementations['panopoly_core']);
    $implementations['panopoly_core'] = $group;
  }
}

/**
 * Implementation hook_element_info_alter().
 */
function panopoly_core_element_info_alter(&$type) {
  // Rather than implementing hook_css_alter(), we'll add a custom pre render 
  // function for the styles elemement. This is to allow us to override 
  // seven_css_alter(), which always runs after any module's implementation.
  if (isset($type['styles']['#pre_render'])) {
    array_unshift($type['styles']['#pre_render'], 'panopoly_core_pre_render_styles');
  }
}

/**
 * Implementation of hook_css_alter()
 */
function panopoly_core_css_alter() { 
  // Deprecated
}

/**
 * Pre render the styles element.
 */
function panopoly_core_pre_render_styles($elements) {
  $css = &$elements['#items'];

  // Installs the jQuery.UI themeroller theme to the theme.
  if (isset($css['misc/ui/jquery.ui.theme.css'])) {
    $css['misc/ui/jquery.ui.theme.css']['data'] = drupal_get_path('module', 'panopoly_core') . '/css/panopoly-jquery-ui-theme.css';
  }
  
  if (isset($css['misc/ui/jquery.ui.dialog.css'])) {
    unset($css['misc/ui/jquery.ui.dialog.css']);
  }
  
  if (isset($css['misc/ui/jquery.ui.tabs.css'])) {
    unset($css['misc/ui/jquery.ui.tabs.css']);
  }

  return $elements;
}

/**
 * Implements hook_date_format_types()
 */
function panopoly_core_date_format_types() {
  return array(
    'panopoly_time' => t('Time'),
    'panopoly_day' => t('Day'),
  );
}

/**
 * Implements hook_date_formats().
 */
function panopoly_core_date_formats() {
  $formats = array();

  $formats[] = array(
    'type' => 'panopoly_time',
    'format' => 'g:ia',
    'locales' => array(),
  );

  $formats[] = array(
    'type' => 'panopoly_day',
    'format' => 'F j, Y',
    'locales' => array(),
  );

  return $formats;
}

/**
 * Helpfer function to get view modes
 */
function panopoly_core_view_mode_options() {
  $entity_info = entity_get_info('node');
  $options = array();
  if (!empty($entity_info['view modes'])) {
    foreach ($entity_info['view modes'] as $mode => $settings) {
      if (!in_array($mode, array('rss', 'search_index', 'search_result', 'token'))) {
        $options[$mode] = $settings['label'];
      }
    }
  }
  return $options;
}
