<?php

/**
 * @file
 * Code for the WS2 Banners feature.
 */

include_once 'ws2_banners.features.inc';

/**
 * Implementation of hook_entity_info_alter().
 */
function ws2_banners_entity_info_alter(&$entity_info) {
// WS2.0 Banners
  $entity_info['fieldable_panels_pane']['bundles']['banners_ws2'] = array(
    'label' => t('Add WS2.0 banner'),
    'description' => t('Add a WS2.0-themed notification banner. Designed to work best in 100% wide rows.'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'ws2_banners') . '/images/icon_banners_WS2.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/%fieldable_panels_panes_type',
      'bundle argument' => 3,
      'real path' => 'admin/structure/fieldable-panels-panes/banners_ws2',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ws2_banners_preprocess_fieldable_panels_pane(&$variables) {
  if (in_array('fieldable_panels_pane__banners_ws2', $variables['theme_hook_suggestions'])) {
    drupal_add_js(drupal_get_path('module', 'ws2_banners')
      . '/js/ws2_banners.js', array('scope' => 'footer', 'group' => JS_THEME, 'weight' => 98));
    drupal_add_css(drupal_get_path('module', 'ws2_banners')
      . '/css/ws2-banners.css', array('weight' => 99));
  }
}

function ws2_banners_preprocess_block__fieldable_panels_panes(&$variables) {
}

/**
 * Implements hook_theme_registry_alter().
 */
function ws2_banners_theme_registry_alter(&$theme_registry) {
  // Added ws2_banners TPL for blocks
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'ws2_banners');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
