<?php

/**
 * @file
 * ASU Directory module
 *
 * This module allows the configuration of custom
 * directory fields, which displays employees in a
 * directory listing from a root department.
 *
 * @author Colton Testamarck (colt@asu.edu)
 *
 */

/*********************************************************************
 * INCLUDES
 *********************************************************************/
include_once 'theme/asu_dir.theme.inc';
include_once 'asu_dir.features.inc';
include_once 'inc/asu_dir.field.inc';
include_once 'inc/asu_dir.helpers.inc';

/*********************************************************************
 * CONFIGS
 *********************************************************************/

// Access Permission Constants
define('ASU_DIRECTORY_ADMIN_CONFIG_SETTINGS', 'Administer ASU Directory Configuration');
define('ASU_DIRECTORY_PAGE_ACCESS', 'access asu directory');

// Form Field Variable Constants
define('ASU_DIRECTORY_TOP_LEVEL_PS_ID', 'ASU');
define('ASU_DIRECTORY_TOP_LEVEL_DEPT_NID', 1342);
define('ASU_DIRECTORY_FORM_CACHE_DURATION', 1);//# of hours, set to 1 initially
define('ASU_DIRECTORY_MODULE_NAME', 'asu_dir');
define('ASU_DIRECTORY_URL', 'https://isearch.asu.edu');

/**********************************************************************
 * HOOKS
 **********************************************************************/






