<?php
/**
 * @file
 * Code for the Webspark News and Events (Step 2) feature.
 */

include_once 'webspark_newsevents.features.inc';

function webspark_newsevents_init() {
  drupal_add_css(drupal_get_path('module', 'webspark_newsevents') . '/css/webspark_newsevents.css', array('weight' => 99, 'group' => CSS_DEFAULT));
  drupal_add_js(drupal_get_path('module', 'webspark_newsevents') . '/js/webspark_newsevents.js', array('scope' => 'footer', 'group' => JS_THEME, 'weight' => 95));
}

/**
 * Implements hook_field_default_field_instances_alter().
 *
 * Set the default image.
 */
function webspark_newsevents_field_default_field_instances_alter(&$fields) {
  if (isset($fields['node-asu_news-field_asunews_image']['settings']['default_image'])) {
    $fields['node-asu_news-field_asunews_image']['settings']['default_image'] = variable_get('webspark_newsevents_asunews_image_fid');
  }
}


/**
* Implements hook_views_api_alter().
*
* Views api is specified by features but we want to add the views-template directory to it.
*/
function webspark_newsevents_views_api_alter(&$apis) {
	if (!empty($apis['webspark_newsevents']) && $apis['webspark_newsevents']['api'] == '3.0') {
		$apis['webspark_newsevents']['template path'] = drupal_get_path('module', 'webspark_newsevents') . '/templates';
	}
}

/**
 * Implements hook_theme().
 */
function webspark_newsevents_theme(){
  return array(
    'views_view_fields__asu-newsevent_images__panel_pane_1' => array(
      'template' => 'templates/views-view-fields--asu-newsevent-images--panel-pane-1',
      'render element' => 'elements',
      'type' => 'module'
    ),
    'views_view_fields__asu-newsevent_images__panel_pane_2' => array(
      'template' => 'templates/views-view-fields--asu-newsevent-images--panel-pane-2',
      'render element' => 'elements',
      'type' => 'module'
    ),
  );
}