<?php
/**
 * @file
 * Drupal needs this blank file.
 */

function asu_isearch_office_hours_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'asu_isearch_admin_settings_form') {
    $office_hours_exists = module_exists('office_hours');
    $form['addons']['isearch_office_hours'] = array(
      '#type' => 'checkbox',
      '#title' => 'Display office hours',
      '#default_value' => variable_get('isearch_office_hours', $office_hours_exists),
      '#description' => t('This option will allow you to add office-hours to profiles locally. Requires office_hours module'),
    );
  }
}
