<?php

/**
 * ASU Brand module.
 *
 * Author: Marcus Anthony (marcus.anthony@asu.edu)
 * Created: 2011-09-21
 */

define('ASU_BRAND_HEADER_VERSION_XML_URL', 'http://asu.edu/asuthemes/headers.xml');
define('ASU_BRAND_HEADER_VERSION_DEFAULT', '4.0');
define('ASU_BRAND_HEADER_BASEPATH_DEFAULT', 'https://asu.edu/asuthemes');
define('ASU_BRAND_HEADER_TEMPLATE_DEFAULT', 'default');
define('ASU_BRAND_FOOTER_COLOR_DEFAULT', '');
define('ASU_BRAND_CACHE_LIFETIME', 172800);
define('ASU_BRAND_PREVIEW_PAGES_DEFAULT', "system/ajax/*\npanels/ajax/*");

/**
 * Implements hook_block_info().
 */
function asu_brand_block_info() {
  // Never cache the header with Drupal's caching system because the contents of
  // the block changes based on if the user is logged in. The included header files
  // are cached manually when then block is viewed in _asu_brand_block_header().
  $blocks['asu_brand_header'] = array(
    'info' => t('ASU Brand: header'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['asu_brand_footer'] = array(
    'info' => t('ASU Brand: footer'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['asu_brand_students_footer'] = array(
    'info' => t('ASU Brand: students footer'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function asu_brand_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'asu_brand_header':
    case 'asu_brand_footer':
    case 'asu_brand_students_footer':
      module_load_include('inc', 'asu_brand', 'asu_brand.admin');
      $form = asu_brand_get_block_configure_form($delta);
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */

function asu_brand_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'asu_brand_header':
      variable_set('asu_brand_header_version', $edit['asu_brand_header_version']);
      variable_set('asu_brand_header_basepath', $edit['asu_brand_header_basepath']);
      variable_set('asu_brand_header_template', $edit['asu_brand_header_template']);
      variable_set('asu_brand_preview_pages', $edit['asu_brand_preview_pages']);
      asu_brand_cache_clear();
      break;
    
    case 'asu_brand_footer':
      variable_set('asu_brand_header_version', $edit['asu_brand_header_version']);
      variable_set('asu_brand_header_basepath', $edit['asu_brand_header_basepath']);
      variable_set('asu_brand_footer_color', $edit['asu_brand_footer_color']);
      variable_set('asu_brand_preview_pages', $edit['asu_brand_preview_pages']);
      asu_brand_cache_clear();
      break;
    
    case 'asu_brand_students_footer':
      variable_set('asu_brand_header_version', $edit['asu_brand_header_version']);
      variable_set('asu_brand_header_basepath', $edit['asu_brand_header_basepath']);
      variable_set('asu_brand_preview_pages', $edit['asu_brand_preview_pages']);
      asu_brand_cache_clear();
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function asu_brand_block_view($delta = '') {
  $block = array();
  $is_preview_path = asu_brand_is_preview_path();
  $preview_text = t('No preview available');
  
  switch ($delta) {
    case 'asu_brand_header':
      $block['subject'] = NULL;
      if ($is_preview_path) {
        $block['content'] = $preview_text;
      }
      else {
        module_load_include('inc', 'asu_brand', 'asu_brand.block');
        $block['content'] = asu_brand_get_block_header();
      }
      break;

    case 'asu_brand_footer':
      $block['subject'] = NULL;
      if ($is_preview_path) {
        $block['content'] = $preview_text;
      }
      else {
        module_load_include('inc', 'asu_brand', 'asu_brand.block');
        $block['content'] = asu_brand_get_block_footer();
      }
      break;
    
    case 'asu_brand_students_footer':
      $block['subject'] = NULL;
      if ($is_preview_path) {
        $block['content'] = $preview_text;
      }
      else {
        module_load_include('inc', 'asu_brand', 'asu_brand.block');
        $block['content'] = asu_brand_get_block_students_footer();
      }
      break;
  }
  return $block;
}

/**
 * Clear block caches.
 * 
 * If called without arguments, clears all asu_brand related items. $cid can be
 * any asu_brand item (without the 'asu_brand:' part.
 */
function asu_brand_cache_clear($cid = '', $wildcard = TRUE) {
  cache_clear_all('asu_brand:' . $cid, 'cache', $wildcard);
}

/**
 * Get list of cache IDs.
 */
function asu_brand_get_cache_ids($reset = FALSE) {
  $cache_ids = &drupal_static(__FUNCTION__);
  if ($reset || !isset($cache_ids)) {
    $cache_ids = array('asu_brand:head', 'asu_brand:header', 'asu_brand:footer', 'asu_brand:students_footer');
  }
  return $cache_ids;
}

/**
 * Determine if path is generating a preview.
 */
function asu_brand_is_preview_path($reset = FALSE) {
  $page_match = &drupal_static(__FUNCTION__);
  if ($reset || !isset($page_match)) {
    $pages = variable_get('asu_brand_preview_pages', ASU_BRAND_PREVIEW_PAGES_DEFAULT);
    // Convert the Drupal path to lowercase.
    $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
    // Compare the lowercase internal and lowercase path alias (if any).
    $page_match = drupal_match_path($path, $pages);
    if ($path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
    }
  }
  return $page_match;
}