<?php
/**
 * Code for the Webspark Extras feature.
 */

include_once 'webspark_extras.features.inc';

/**
 * @file - Forces custom functionality on initial bootstrapping
 */

/**
 * Implements hook_boot()
 *
 * Ensures that all pages are forced to HTTPS if site is on Pantheon
 */
function webspark_extras_boot() {
  global $install_state;
  if (!$install_state) {
    if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) {
      if (!isset($_SERVER['HTTP_X_SSL']) || $_SERVER['HTTP_X_SSL'] != 'ON') {
        header('HTTP/1.0 301 Moved Permanently');
        header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
        exit();
      }
    }
  }
}