<?php
/**
 * @file
 * Code for the Webspark banner feature.
 */

include_once 'webspark_banner.features.inc';

function webspark_banner_entity_info_alter(&$entity_info) {
  // Webspark Banner Widget.
  $entity_info['fieldable_panels_pane']['bundles']['banner'] = array(
    'label' => t('Add title banner'),
    'description' => t('Add a 1170 x 200 px image title banner to the top row'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'webspark_banner') . '/images/icon_banner.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/banner',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_fieldable_panels_pane().
 */
function webspark_banner_preprocess_fieldable_panels_pane(&$variables){
  if($variables['elements']['#bundle'] === 'banner'){
    $title = $variables['elements']['#fieldable_panels_pane']->title;
    $variables['elements']['title'] = array(
      '#theme' => 'html_tag',
      '#tag' => 'h2',
      '#value' => $title
    );
  }
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function webspark_banner_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle']) && $variables['content']['#bundle']==='banner' ){
    $variables['title'] = '';
  }
}

/**
 * Implements hook_theme().
 */
function webspark_banner_theme(){
  return array(
    'fieldable_panels_pane__banner' => array(
      'template' => 'templates/fieldable-panels-pane--banner',
      'render element' => 'elements',
      'type' => 'module'
    )
  );
}

function webspark_banner_init() {
	drupal_add_js(drupal_get_path('module', 'webspark_banner') . '/js/webspark_banner.js', array('scope' => 'footer', 'group' => JS_THEME, 'weight' => 95));
}
