<?php

include_once('panopoly_images.features.inc');

/**
 * Implementation of hook_init()
 */
function panopoly_images_init() {

  // Adding the panopoly images file to the theme so it will show up in the WYSIWYG
  drupal_add_css(drupal_get_path('module', 'panopoly_images') . '/panopoly-images.css', array('group' => CSS_THEME));
}


/**
 * Implementation of drupal_alter() for media_wysiwyg_allowed_view_modes
 */
function panopoly_images_media_wysiwyg_allowed_view_modes_alter(&$options, $context) {

  // Relabel some options
  $options['default']['label'] = t('Full Size');
  $options['teaser']['label'] = t('Half Size');
  $options['preview']['label'] = t('Thumbnail');
}

/**
 * Implementation of hook_form_alter()
 */
function panopoly_images_form_alter(&$form, &$form_state, $form_id) {

  // Improve the media upload form
  if (!empty($form['upload'])) {
    $form['upload']['#size'] = 30;
  }

  // Warm the image style cache by preloading some images. This is needed when the images are
  // added in the WYSIWYG so they will be fully rendered and can be sized on insert.
  if ($form_id == 'media_format_form') {
    $form['preload'] = array(
      '#prefix' => '<div style="display: none">',
      '#suffix' => '</div>',
    );
    $image_path = $form['#media']->uri;
    $image_formats = array('panopoly_image_full', 'panopoly_image_half', 'panopoly_image_quarter');
    foreach ($image_formats as $format) {
      $form['preload'][$format] = array(
        '#markup' => theme('image', array('path' => image_style_url($format, $image_path))),
      );
    }
  }

  // Set the default media style to be default
  if ($form_id == 'media_format_form' && !empty($form['options']['format'])) {
    $form['options']['format']['#default_value'] = 'default';
  }
}

/**
 * Implementation of hook_preprocess_image_style()
 */
function panopoly_images_preprocess_image_style(&$variables) {
  $variables['attributes']['class'][] = str_replace('_', '-', $variables['style_name']);
}
