<?php
/**
 * Placeholder module for features in subdirectories
 * Code added to activate theme specific modules & configuration
 */

/**
 * Implements hook_menu_alter() - builds on existing menu callback
 */

function webspark_featurescustom_menu_alter (&$items) {
  // Modifying callback for theme selection function to include our own functionality
  $items['admin/appearance/default']['page callback'] = 'webspark_featurescustom_theme_check';
}

/**
 * Custom menu callback
 */
function webspark_featurescustom_theme_check () {
  // Checking if the selected theme is our theme & calling function to active modules/configuration
  module_load_include('inc', 'system', 'system.admin.inc');
  $theme_request = $_REQUEST['theme'];
  if ($theme_request == 'innovation') {
    _webspark_featurescustom_enable_config($theme_request);
  }
  system_theme_default();
}

/**
 * On switch-over from Webspark Classic to Innovation theme, do the following:
 */
function _webspark_featurescustom_enable_config($theme) {
  // Enabling Innovation-related modules if they are not enabled
  $modules = array();
  // Contrib module dependencies for features
  $modules[] = 'backgroundfield';
  $modules[] = 'chosen';
  $modules[] = 'easy_breadcrumb';
  $modules[] = 'entity_view_mode';
  $modules[] = 'flexslider';
  $modules[] = 'fontawesome';
  $modules[] = 'google_appliance';
  $modules[] = 'maxlength';
  $modules[] = 'panels_tabs';
  $modules[] = 'uuid_features';
  $modules[] = 'video_embed_field';
  $modules[] = 'wysiwyg_template';
  $modules[] = 'asu_spotlight';
  $modules[] = 'mega_footer';
  // OpenASU custom modules, features
  $modules[] = 'asu_gsa';
  $modules[] = 'asu_maps_enhanced';
  $modules[] = 'webspark_wysiwyg';
  $modules[] = 'webspark_panels_styles';
  $modules[] = 'webspark_banner';
  $modules[] = 'webspark_breadcrumbs';
  $modules[] = 'webspark_content_callout';
  $modules[] = 'webspark_hero';
  $modules[] = 'webspark_jumbohero';
  $modules[] = 'webspark_megamenu';
  $modules[] = 'mega_footer_menu';
  $modules[] = 'webspark_extras';
  module_enable($modules,TRUE);
  watchdog('theme update', 'Modules enabled for ' . $theme . ' - ' . implode(',', $modules));

  // WEBSPARK-448, 509
  // Add setting for updating header to proper version
  variable_set('asu_brand_header_version', '4.3');
  // Update header file name to default
  variable_set('asu_brand_header_template', 'default');
  // Update header basepath
  variable_set('asu_brand_header_basepath', 'http://www.asu.edu/asuthemes');
  watchdog('theme update', 'Updated header values for ' . $theme);

  // WEBSPARK-509 - Swap out system main-menu with TB Mega Menu main-menu on
  // theme update.
  db_update('block')
    ->fields(array(
        'region' => 'menu',
        'status' => '1',
        'weight' => '-100'
      )
    )
    ->condition('module', 'tb_megamenu')
    ->condition('delta', 'main-menu')
    ->execute();
  db_update('block')
    ->fields(array(
        'region' => '-1',
        'status' => '0',
        'weight' => '0'
      )
    )
    ->condition('module', 'system')
    ->condition('delta', 'main-menu')
    ->execute();
  // disable ASU Students block
  db_update('block')
    ->fields(array(
        'region' => '-1',
        'status' => '0',
        'weight' => '0'
      )
    )
    ->condition('module', 'asu_brand')
    ->condition('delta', 'asu_brand_students_footer')
    ->execute();
  watchdog('theme update', 'Updated nav menu blocks for ' . $theme);
}


/**
 * Implementation of hook_entity_info_alter()
 */
function webspark_featurescustom_entity_info_alter(&$entity_info) {
  // Changing name of Basic Image widget for clarity
  $entity_info['fieldable_panels_pane']['bundles']['image'] = array(
    'label' => t('Add responsive image'),
    'description' => t('Add 100%-wide responsive image'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/image',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  // Changing description of Basic text for clarity
  $entity_info['fieldable_panels_pane']['bundles']['text'] = array(
    'label' => t('Add text'),
    'description' => t('Add text and media'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/text',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
