<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_init().
 **/
function webspark_megamenu_init() {
  drupal_add_js(libraries_get_path('emulatetab') . '/src/emulatetab.joelpurra.min.js');
  $ws2_check = _webspark_featurescustom_ws2_check();
  drupal_add_js(drupal_get_path('module', 'webspark_megamenu') . '/js/webspark_megamenu' . $ws2_check . '.js', 'file');
  drupal_add_css(drupal_get_path('module', 'webspark_megamenu') . '/css/webspark_megamenu' . $ws2_check . '.css', array('weight' => 99, 'group' => CSS_DEFAULT));
}

/**
 * Implements hook_page_alter().
 **/
function webspark_megamenu_page_alter(&$page) {
  $ws2_check = _webspark_featurescustom_ws2_check();
  drupal_add_js(drupal_get_path('module', 'webspark_megamenu').'/js/webspark_megamenu_pre' . $ws2_check . '.js', array('scope'=>'header'));
}

/**
 * Implements hook_libraries_info().
 */
function webspark_megamenu_libraries_info() {
  $libraries['emulatetab'] = array(
    'name' => 'EmulateTab',
    'vendor url' => 'https://github.com/joelpurra/emulatetab',
    'download url' => 'https://raw.githubusercontent.com/joelpurra/emulatetab/gh-pages/dist/emulatetab.joelpurra.min.js',
    'path' => 'profiles/openasu/libraries/emulatetab/src',
    // Version v0.2.8
    'files' => array(
      'js' => array('emulatetab.joelpurra.js'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webspark_megamenu_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  // Adds unit title to /admin/config/system/site-information
  $form['site_information']['site_unit_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Unit name',
    '#default_value' => variable_get('site_unit_name', ''),
    '#description' => 'Parent unit at ASU. This will appear in the global header above the subdomain (site name). (Optional)',
    '#weight' => -1,
  );
  $form['site_information']['site_name']['#weight'] = -2;
}
