<?php
/**
 * @file
 * Install and update hooks.
 */
function asu_events_enable() {
  drupal_set_message("Prevented enabling deprecated module.");
  module_disable(array('asu_events'));
  drupal_uninstall_modules(array('asu_events'));
}

function asu_events_uninstall(){
  $modules = array('asu_events_importer', 'asu_feeds2');
  foreach($modules as $module){
    if( module_exists($module)) {
      module_disable(array($module));
      drupal_uninstall_modules(array($module));
    }
    drupal_uninstall_schema($module);
  }
}

function _asu_events_create_taxonomy() {
  $new_vocab = (object) array(
    'name' => 'ASU Events Category',
    'description' => 'This vocabulary has a special purpose',
    'machine_name' => 'asu_events_category',
  );
  taxonomy_vocabulary_save($new_vocab);
  $new_vocab = (object) array(
    'name' => 'ASU Events Type',
    'description' => 'This vocabulary has a special purpose',
    'machine_name' => 'asu_events_type',
  );
  taxonomy_vocabulary_save($new_vocab);
  $new_vocab = (object) array(
    'name' => 'ASU Events Audience',
    'description' => 'This vocabulary has a special purpose',
    'machine_name' => 'asu_events_audience',
  );
  taxonomy_vocabulary_save($new_vocab);
}

/**
 * Disables page variants so that Events nodes are not panelized
 * @param  string   $page_name   Name of the page with the variants
 * @param  array()  $variant_ids String array with id names of the variants
 * @return void
 */
function _asu_events_disable_page_variants($page_name, $variant_ids) {

  $page = page_manager_get_page_cache($page_name);
  if (!empty($page)) {
    foreach($variant_ids as $id) {
      if(isset($page->handler_info[$id])) {
        $page->handler_info[$id]['disabled'] = true;
        $page->handler_info[$id]['changed'] = PAGE_MANAGER_CHANGED_STATUS;
      }
    }

    page_manager_save_page_cache($page);
  }
}

/**
 * Add proper permisions for the download links
 */
function asu_events_update_7001() {
  $permissions = array('download any image files');
  foreach(array('anonymous user', 'authenticated user') as $role_name) {
    $role = user_role_load_by_name($role_name);
    user_role_grant_permissions($role->rid, $permissions);
  }
}

/**
 * Update the display for ddate field so addtocal will download ics
 */
function asu_events_update_7002() {
  // Fetch an instance info array.
  $instance_info = field_info_instance('node', 'field_asuevent_very_start_date', 'asu_event');
  // Change a single property in the instance definition.
  $instance_info['display']['default'] = array(
    'type' => 'addtocal_view',
    'label' => 'hidden',
    'weight' => 5,
    'module' => 'addtocal',
    'settings' => array(
      'format_type' => 'medium',
      'fromto' => 'both',
    ),
  );
  // Write the changed definition back.
  field_update_instance($instance_info);

  cache_clear_all();
}

/**
 * Disable views displays for Example page and feed.
 */
function _asu_events_disable_views_events_page($name) {
  $t = get_t();

  $views_name = $name;
  $views_displays = array('page');

  $disabled_displays = array();
  $variables = array('@view_name' => $views_name);

  $view = views_get_view($views_name);
  if ($view) {
    foreach ($views_displays as $display_name) {
      if (isset($view->display[$display_name])) {
        $view->display[$display_name]->display_options['enabled'] = FALSE;
        $disabled_displays[] = $display_name;
      }
    }
    views_save_view($view);
  }
  else {
    $message = 'Unable to load @view_name from views.';
    //throw new DrupalUpdateException($t($message, $variables));
  }

  if (count($disabled_displays)) {
    $message = 'Disabled @view_name views displays named @displays. ';
    $variables['@displays'] = implode(', ', $disabled_displays);

    $missing_displays = array_diff($views_displays, $disabled_displays);
    if (count($missing_displays)) {
      $message .= 'Missing @view_name views displays named @displays could not be disabled. ';
      $variables['@missing'] = implode(', ', $missing_displays);
    }
  }
  else {
    $message = 'Nothing to do. No @view_name views displays named @displays found to disable. ';
    $variables['@displays'] = implode(', ', $views_displays);
  }

  return $t($message, $variables);
}

function _asu_events_create_node_type() {
  $type = node_type_load('asu_event');
  if (!$type) {
    $type = array(
        'type' => 'asu_event',
        'name' => 'ASU Event',
        'base' => 'node_content',
        'description' => '',
        'has_title' => '1',
        'title_label' => 'Title',
        'custom' => '1',
        'modified' => '1',
        'locked' => '0',
    );

    $type = node_type_set_defaults($type);

    node_type_save($type);
    node_add_body_field($type);
  }
}

function _asu_events_create_fields() {
  $display_arr = array(
    'events_featured_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'events_full_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'events_list_page_featured_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'events_list_page_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'events_small_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'featured' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_featured_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_list_page_compact_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_list_page_featured_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_list_page_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_medium_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'news_small_teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
    'teaser' => array(
      'label' => 'above',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 0,
    ),
  );
  $data = array(
    'fields' => array(
      // @TODO - ASU Social Share - reuse?
      // 'field_asu_social_share' => array(
      //   'entity_types' => array(),
      //   'foreign keys' => array(),
      //   'indexes' => array(),
      //   'settings' => array(),
      //   'translatable' => '0',
      //   'storage' => array(
      //     'type' => 'field_sql_storage',
      //     'settings' => array(),
      //     'module' => 'field_sql_storage',
      //     'active' => '1',
      //     'details' => array(),
      //   ),
      //   'field_name' => 'field_asu_social_share',
      //   'type' => 'gigya_sharebar',
      //   'module' => 'gigya',
      //   'active' => '1',
      //   'locked' => '0',
      //   'cardinality' => '1',
      //   'deleted' => '0',
      //   'columns' => array(),
      //   'bundles' => array(
      //     'node' => array(
      //       0 => 'asu_event',
      //     ),
      //   ),
      // ),
      'field_asuevent_artists' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_artists' => array(
                  'value' => 'field_asuevent_artists_value',
                  'format' => 'field_asuevent_artists_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_artists' => array(
                  'value' => 'field_asuevent_artists_value',
                  'format' => 'field_asuevent_artists_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_artists',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_campus' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_campus' => array(
                  'value' => 'field_asuevent_campus_value',
                  'format' => 'field_asuevent_campus_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_campus' => array(
                  'value' => 'field_asuevent_campus_value',
                  'format' => 'field_asuevent_campus_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_campus',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_closing_recep' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_closing_recep' => array(
                  'value' => 'field_asuevent_closing_recep_value',
                  'format' => 'field_asuevent_closing_recep_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_closing_recep' => array(
                  'value' => 'field_asuevent_closing_recep_value',
                  'format' => 'field_asuevent_closing_recep_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_closing_recep',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_contact_name' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_contact_name' => array(
                  'value' => 'field_asuevent_contact_name_value',
                  'format' => 'field_asuevent_contact_name_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_contact_name' => array(
                  'value' => 'field_asuevent_contact_name_value',
                  'format' => 'field_asuevent_contact_name_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_contact_name',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_curator' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_curator' => array(
                  'value' => 'field_asuevent_curator_value',
                  'format' => 'field_asuevent_curator_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_curator' => array(
                  'value' => 'field_asuevent_curator_value',
                  'format' => 'field_asuevent_curator_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_curator',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_date' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'cache_count' => 4,
          'cache_enabled' => 0,
          'granularity' => array(
            'day' => 'day',
            'hour' => 'hour',
            'minute' => 'minute',
            'month' => 'month',
            'second' => 0,
            'year' => 'year',
          ),
          'timezone_db' => '',
          'todate' => 'optional',
          'tz_handling' => 'none',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_date' => array(
                  'value' => 'field_asuevent_date_value',
                  'value2' => 'field_asuevent_date_value2',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_date' => array(
                  'value' => 'field_asuevent_date_value',
                  'value2' => 'field_asuevent_date_value2',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_date',
        'type' => 'date',
        'module' => 'date',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 20,
            'not null' => FALSE,
            'sortable' => TRUE,
            'views' => TRUE,
          ),
          'value2' => array(
            'type' => 'varchar',
            'length' => 20,
            'not null' => FALSE,
            'sortable' => TRUE,
            'views' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_dept' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_dept' => array(
                  'value' => 'field_asuevent_dept_value',
                  'format' => 'field_asuevent_dept_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_dept' => array(
                  'value' => 'field_asuevent_dept_value',
                  'format' => 'field_asuevent_dept_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_dept',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_display_date' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_display_date' => array(
                  'value' => 'field_asuevent_display_date_value',
                  'format' => 'field_asuevent_display_date_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_display_date' => array(
                  'value' => 'field_asuevent_display_date_value',
                  'format' => 'field_asuevent_display_date_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_display_date',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_email' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => '60',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_email' => array(
                  'value' => 'field_asuevent_email_value',
                  'format' => 'field_asuevent_email_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_email' => array(
                  'value' => 'field_asuevent_email_value',
                  'format' => 'field_asuevent_email_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_email',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => '60',
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_email2' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_email2' => array(
                  'email' => 'field_asuevent_email2_email',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_email2' => array(
                  'email' => 'field_asuevent_email2_email',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_email2',
        'type' => 'email',
        'module' => 'email',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'email' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_email_view' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_email_view' => array(
                  'vname' => 'field_asuevent_email_view_vname',
                  'vargs' => 'field_asuevent_email_view_vargs',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_email_view' => array(
                  'vname' => 'field_asuevent_email_view_vname',
                  'vargs' => 'field_asuevent_email_view_vargs',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_email_view',
        'type' => 'viewfield',
        'module' => 'viewfield',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'vname' => array(
            'type' => 'varchar',
            'not null' => FALSE,
            'length' => 128,
          ),
          'vargs' => array(
            'type' => 'varchar',
            'not null' => FALSE,
            'length' => 255,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_image' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'fid' => array(
            'table' => 'file_managed',
            'columns' => array(
              'fid' => 'fid',
            ),
          ),
        ),
        'indexes' => array(
          'fid' => array(
            0 => 'fid',
          ),
        ),
        'settings' => array(
          'default_image' => 0,
          'uri_scheme' => 'public',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_image' => array(
                  'fid' => 'field_asuevent_image_fid',
                  'alt' => 'field_asuevent_image_alt',
                  'title' => 'field_asuevent_image_title',
                  'width' => 'field_asuevent_image_width',
                  'height' => 'field_asuevent_image_height',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_image' => array(
                  'fid' => 'field_asuevent_image_fid',
                  'alt' => 'field_asuevent_image_alt',
                  'title' => 'field_asuevent_image_title',
                  'width' => 'field_asuevent_image_width',
                  'height' => 'field_asuevent_image_height',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_image',
        'type' => 'image',
        'module' => 'image',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'fid' => array(
            'description' => 'The {file_managed}.fid being referenced in this field.',
            'type' => 'int',
            'not null' => FALSE,
            'unsigned' => TRUE,
          ),
          'alt' => array(
            'description' => 'Alternative image text, for the image\'s \'alt\' attribute.',
            'type' => 'varchar',
            'length' => 512,
            'not null' => FALSE,
          ),
          'title' => array(
            'description' => 'Image title text, for the image\'s \'title\' attribute.',
            'type' => 'varchar',
            'length' => 1024,
            'not null' => FALSE,
          ),
          'width' => array(
            'description' => 'The width of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
          'height' => array(
            'description' => 'The height of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
            1 => 'law_events',
          ),
        ),
      ),
      'field_asuevent_image_view' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_image_view' => array(
                  'vname' => 'field_asuevent_image_view_vname',
                  'vargs' => 'field_asuevent_image_view_vargs',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_image_view' => array(
                  'vname' => 'field_asuevent_image_view_vname',
                  'vargs' => 'field_asuevent_image_view_vargs',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_image_view',
        'type' => 'viewfield',
        'module' => 'viewfield',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'vname' => array(
            'type' => 'varchar',
            'not null' => FALSE,
            'length' => 128,
          ),
          'vargs' => array(
            'type' => 'varchar',
            'not null' => FALSE,
            'length' => 255,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_img_alt' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_img_alt' => array(
                  'value' => 'field_asuevent_img_alt_value',
                  'format' => 'field_asuevent_img_alt_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_img_alt' => array(
                  'value' => 'field_asuevent_img_alt_value',
                  'format' => 'field_asuevent_img_alt_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_img_alt',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_img_caption' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_img_caption' => array(
                  'value' => 'field_asuevent_img_caption_value',
                  'format' => 'field_asuevent_img_caption_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_img_caption' => array(
                  'value' => 'field_asuevent_img_caption_value',
                  'format' => 'field_asuevent_img_caption_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_img_caption',
        'type' => 'text_long',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'text',
            'size' => 'big',
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_location' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_location' => array(
                  'value' => 'field_asuevent_location_value',
                  'format' => 'field_asuevent_location_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_location' => array(
                  'value' => 'field_asuevent_location_value',
                  'format' => 'field_asuevent_location_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_location',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_more_info' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_more_info' => array(
                  'url' => 'field_asuevent_more_info_url',
                  'title' => 'field_asuevent_more_info_title',
                  'attributes' => 'field_asuevent_more_info_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_more_info' => array(
                  'url' => 'field_asuevent_more_info_url',
                  'title' => 'field_asuevent_more_info_title',
                  'attributes' => 'field_asuevent_more_info_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_more_info',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_nid' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_nid' => array(
                  'value' => 'field_asuevent_nid_value',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_nid' => array(
                  'value' => 'field_asuevent_nid_value',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_nid',
        'type' => 'number_integer',
        'module' => 'number',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'int',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_nonacademic_unit' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_nonacademic_unit' => array(
                  'value' => 'field_asuevent_nonacademic_unit_value',
                  'format' => 'field_asuevent_nonacademic_unit_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_nonacademic_unit' => array(
                  'value' => 'field_asuevent_nonacademic_unit_value',
                  'format' => 'field_asuevent_nonacademic_unit_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_nonacademic_unit',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_opening_recep' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_opening_recep' => array(
                  'value' => 'field_asuevent_opening_recep_value',
                  'format' => 'field_asuevent_opening_recep_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_opening_recep' => array(
                  'value' => 'field_asuevent_opening_recep_value',
                  'format' => 'field_asuevent_opening_recep_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_opening_recep',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_other_dept' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_other_dept' => array(
                  'value' => 'field_asuevent_other_dept_value',
                  'format' => 'field_asuevent_other_dept_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_other_dept' => array(
                  'value' => 'field_asuevent_other_dept_value',
                  'format' => 'field_asuevent_other_dept_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_other_dept',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_past_exhibitions' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_past_exhibitions' => array(
                  'value' => 'field_asuevent_past_exhibitions_value',
                  'format' => 'field_asuevent_past_exhibitions_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_past_exhibitions' => array(
                  'value' => 'field_asuevent_past_exhibitions_value',
                  'format' => 'field_asuevent_past_exhibitions_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_past_exhibitions',
        'type' => 'text_long',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'text',
            'size' => 'big',
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_pdf' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_pdf' => array(
                  'url' => 'field_asuevent_pdf_url',
                  'title' => 'field_asuevent_pdf_title',
                  'attributes' => 'field_asuevent_pdf_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_pdf' => array(
                  'url' => 'field_asuevent_pdf_url',
                  'title' => 'field_asuevent_pdf_title',
                  'attributes' => 'field_asuevent_pdf_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_pdf',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_phone' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => '60',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_phone' => array(
                  'value' => 'field_asuevent_phone_value',
                  'format' => 'field_asuevent_phone_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_phone' => array(
                  'value' => 'field_asuevent_phone_value',
                  'format' => 'field_asuevent_phone_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_phone',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => '60',
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_press_release' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_press_release' => array(
                  'url' => 'field_asuevent_press_release_url',
                  'title' => 'field_asuevent_press_release_title',
                  'attributes' => 'field_asuevent_press_release_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_press_release' => array(
                  'url' => 'field_asuevent_press_release_url',
                  'title' => 'field_asuevent_press_release_title',
                  'attributes' => 'field_asuevent_press_release_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_press_release',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_price' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_price' => array(
                  'value' => 'field_asuevent_price_value',
                  'format' => 'field_asuevent_price_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_price' => array(
                  'value' => 'field_asuevent_price_value',
                  'format' => 'field_asuevent_price_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_price',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_register_other' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_register_other' => array(
                  'value' => 'field_asuevent_register_other_value',
                  'format' => 'field_asuevent_register_other_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_register_other' => array(
                  'value' => 'field_asuevent_register_other_value',
                  'format' => 'field_asuevent_register_other_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_register_other',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_registration_url' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_registration_url' => array(
                  'url' => 'field_asuevent_registration_url_url',
                  'title' => 'field_asuevent_registration_url_title',
                  'attributes' => 'field_asuevent_registration_url_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_registration_url' => array(
                  'url' => 'field_asuevent_registration_url_url',
                  'title' => 'field_asuevent_registration_url_title',
                  'attributes' => 'field_asuevent_registration_url_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_registration_url',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_room' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_room' => array(
                  'value' => 'field_asuevent_room_value',
                  'format' => 'field_asuevent_room_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_room' => array(
                  'value' => 'field_asuevent_room_value',
                  'format' => 'field_asuevent_room_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_room',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_rsvp_other' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_rsvp_other' => array(
                  'value' => 'field_asuevent_rsvp_other_value',
                  'format' => 'field_asuevent_rsvp_other_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_rsvp_other' => array(
                  'value' => 'field_asuevent_rsvp_other_value',
                  'format' => 'field_asuevent_rsvp_other_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_rsvp_other',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_rsvp_url' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_rsvp_url' => array(
                  'url' => 'field_asuevent_rsvp_url_url',
                  'title' => 'field_asuevent_rsvp_url_title',
                  'attributes' => 'field_asuevent_rsvp_url_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_rsvp_url' => array(
                  'url' => 'field_asuevent_rsvp_url_url',
                  'title' => 'field_asuevent_rsvp_url_title',
                  'attributes' => 'field_asuevent_rsvp_url_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_rsvp_url',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_sponsorship' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_sponsorship' => array(
                  'value' => 'field_asuevent_sponsorship_value',
                  'format' => 'field_asuevent_sponsorship_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_sponsorship' => array(
                  'value' => 'field_asuevent_sponsorship_value',
                  'format' => 'field_asuevent_sponsorship_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_sponsorship',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_subtitle' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_subtitle' => array(
                  'value' => 'field_asuevent_subtitle_value',
                  'format' => 'field_asuevent_subtitle_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_subtitle' => array(
                  'value' => 'field_asuevent_subtitle_value',
                  'format' => 'field_asuevent_subtitle_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_subtitle',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_tax_audience' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'asu_events_audience',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_tax_audience' => array(
                  'tid' => 'field_asuevent_tax_audience_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_tax_audience' => array(
                  'tid' => 'field_asuevent_tax_audience_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_tax_audience',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_tax_category' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'asu_events_category',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_tax_category' => array(
                  'tid' => 'field_asuevent_tax_category_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_tax_category' => array(
                  'tid' => 'field_asuevent_tax_category_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_tax_category',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_tax_type' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'asu_events_type',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_tax_type' => array(
                  'tid' => 'field_asuevent_tax_type_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_tax_type' => array(
                  'tid' => 'field_asuevent_tax_type_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_tax_type',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_thumb_img' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'fid' => array(
            'table' => 'file_managed',
            'columns' => array(
              'fid' => 'fid',
            ),
          ),
        ),
        'indexes' => array(
          'fid' => array(
            0 => 'fid',
          ),
        ),
        'settings' => array(
          'default_image' => 2329,
          'uri_scheme' => 'public',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_thumb_img' => array(
                  'fid' => 'field_asuevent_thumb_img_fid',
                  'alt' => 'field_asuevent_thumb_img_alt',
                  'title' => 'field_asuevent_thumb_img_title',
                  'width' => 'field_asuevent_thumb_img_width',
                  'height' => 'field_asuevent_thumb_img_height',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_thumb_img' => array(
                  'fid' => 'field_asuevent_thumb_img_fid',
                  'alt' => 'field_asuevent_thumb_img_alt',
                  'title' => 'field_asuevent_thumb_img_title',
                  'width' => 'field_asuevent_thumb_img_width',
                  'height' => 'field_asuevent_thumb_img_height',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_thumb_img',
        'type' => 'image',
        'module' => 'image',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'fid' => array(
            'description' => 'The {file_managed}.fid being referenced in this field.',
            'type' => 'int',
            'not null' => FALSE,
            'unsigned' => TRUE,
          ),
          'alt' => array(
            'description' => 'Alternative image text, for the image\'s \'alt\' attribute.',
            'type' => 'varchar',
            'length' => 512,
            'not null' => FALSE,
          ),
          'title' => array(
            'description' => 'Image title text, for the image\'s \'title\' attribute.',
            'type' => 'varchar',
            'length' => 1024,
            'not null' => FALSE,
          ),
          'width' => array(
            'description' => 'The width of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
          'height' => array(
            'description' => 'The height of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_ticketing_url' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_ticketing_url' => array(
                  'url' => 'field_asuevent_ticketing_url_url',
                  'title' => 'field_asuevent_ticketing_url_title',
                  'attributes' => 'field_asuevent_ticketing_url_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_ticketing_url' => array(
                  'url' => 'field_asuevent_ticketing_url_url',
                  'title' => 'field_asuevent_ticketing_url_title',
                  'attributes' => 'field_asuevent_ticketing_url_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_ticketing_url',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_unit' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_unit' => array(
                  'value' => 'field_asuevent_unit_value',
                  'format' => 'field_asuevent_unit_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_unit' => array(
                  'value' => 'field_asuevent_unit_value',
                  'format' => 'field_asuevent_unit_format',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_unit',
        'type' => 'text',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_url' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_url' => array(
                  'url' => 'field_asuevent_url_url',
                  'title' => 'field_asuevent_url_title',
                  'attributes' => 'field_asuevent_url_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_url' => array(
                  'url' => 'field_asuevent_url_url',
                  'title' => 'field_asuevent_url_title',
                  'attributes' => 'field_asuevent_url_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_url',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_asuevent_very_start_date' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'cache_count' => 4,
          'cache_enabled' => 0,
          'granularity' => array(
            'day' => 'day',
            'hour' => 'hour',
            'minute' => 'minute',
            'month' => 'month',
            'second' => 0,
            'year' => 'year',
          ),
          'repeat' => 0,
          'timezone_db' => '',
          'todate' => 'optional',
          'tz_handling' => 'none',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_asuevent_very_start_date' => array(
                  'value' => 'field_asuevent_very_start_date_value',
                  'value2' => 'field_asuevent_very_start_date_value2',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_asuevent_very_start_date' => array(
                  'value' => 'field_asuevent_very_start_date_value',
                  'value2' => 'field_asuevent_very_start_date_value2',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_asuevent_very_start_date',
        'type' => 'date',
        'module' => 'date',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'varchar',
            'length' => 20,
            'not null' => FALSE,
            'sortable' => TRUE,
            'views' => TRUE,
          ),
          'value2' => array(
            'type' => 'varchar',
            'length' => 20,
            'not null' => FALSE,
            'sortable' => TRUE,
            'views' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_college_unit' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'college_unit',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_college_unit' => array(
                  'tid' => 'field_college_unit_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_college_unit' => array(
                  'tid' => 'field_college_unit_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_college_unit',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_constituent_type' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'constituent_type',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_constituent_type' => array(
                  'tid' => 'field_constituent_type_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_constituent_type' => array(
                  'tid' => 'field_constituent_type_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_constituent_type',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_news',
            1 => 'asu_event',
          ),
        ),
      ),
      'field_event_location' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_event_location' => array(
                  'url' => 'field_event_location_url',
                  'title' => 'field_event_location_title',
                  'attributes' => 'field_event_location_attributes',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_event_location' => array(
                  'url' => 'field_event_location_url',
                  'title' => 'field_event_location_title',
                  'attributes' => 'field_event_location_attributes',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_event_location',
        'type' => 'link_field',
        'module' => 'link',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'url' => array(
            'type' => 'varchar',
            'length' => 2048,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'title' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
            'sortable' => TRUE,
          ),
          'attributes' => array(
            'type' => 'text',
            'size' => 'medium',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_event_map' => array(
        'entity_types' => array(),
        'foreign keys' => array(),
        'indexes' => array(),
        'settings' => array(),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_event_map' => array(
                  'description' => 'field_event_map_description',
                  'map_items' => 'field_event_map_map_items',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_event_map' => array(
                  'description' => 'field_event_map_description',
                  'map_items' => 'field_event_map_map_items',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_event_map',
        'type' => 'asu_maps_enhanced',
        'module' => 'asu_maps_enhanced',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'description' => array(
            'type' => 'text',
            'not null' => FALSE,
          ),
          'map_items' => array(
            'type' => 'text',
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_event_type' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'asu_events_type',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_event_type' => array(
                  'tid' => 'field_event_type_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_event_type' => array(
                  'tid' => 'field_event_type_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_event_type',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_interests' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'interests',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_interests' => array(
                  'tid' => 'field_interests_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_interests' => array(
                  'tid' => 'field_interests_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_interests',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_news',
            1 => 'asu_event',
          ),
        ),
      ),
      'field_locations' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'tid' => array(
            'table' => 'taxonomy_term_data',
            'columns' => array(
              'tid' => 'tid',
            ),
          ),
        ),
        'indexes' => array(
          'tid' => array(
            0 => 'tid',
          ),
        ),
        'settings' => array(
          'allowed_values' => array(
            0 => array(
              'vocabulary' => 'locations',
              'parent' => 0,
            ),
          ),
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_locations' => array(
                  'tid' => 'field_locations_tid',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_locations' => array(
                  'tid' => 'field_locations_tid',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_locations',
        'type' => 'taxonomy_term_reference',
        'module' => 'taxonomy',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '-1',
        'deleted' => '0',
        'columns' => array(
          'tid' => array(
            'type' => 'int',
            'unsigned' => TRUE,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_news',
            1 => 'asu_event',
          ),
        ),
      ),
      'field_news_events_thumb_img' => array(
        'entity_types' => array(),
        'foreign keys' => array(
          'fid' => array(
            'table' => 'file_managed',
            'columns' => array(
              'fid' => 'fid',
            ),
          ),
        ),
        'indexes' => array(
          'fid' => array(
            0 => 'fid',
          ),
        ),
        'settings' => array(
          'default_image' => '14544',
          'uri_scheme' => 'public',
        ),
        'translatable' => '0',
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_news_events_thumb_img' => array(
                  'fid' => 'field_news_events_thumb_img_fid',
                  'alt' => 'field_news_events_thumb_img_alt',
                  'title' => 'field_news_events_thumb_img_title',
                  'width' => 'field_news_events_thumb_img_width',
                  'height' => 'field_news_events_thumb_img_height',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_news_events_thumb_img' => array(
                  'fid' => 'field_news_events_thumb_img_fid',
                  'alt' => 'field_news_events_thumb_img_alt',
                  'title' => 'field_news_events_thumb_img_title',
                  'width' => 'field_news_events_thumb_img_width',
                  'height' => 'field_news_events_thumb_img_height',
                ),
              ),
            ),
          ),
        ),
        'field_name' => 'field_news_events_thumb_img',
        'type' => 'image',
        'module' => 'image',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'fid' => array(
            'description' => 'The {file_managed}.fid being referenced in this field.',
            'type' => 'int',
            'not null' => FALSE,
            'unsigned' => TRUE,
          ),
          'alt' => array(
            'description' => 'Alternative image text, for the image\'s \'alt\' attribute.',
            'type' => 'varchar',
            'length' => 512,
            'not null' => FALSE,
          ),
          'title' => array(
            'description' => 'Image title text, for the image\'s \'title\' attribute.',
            'type' => 'varchar',
            'length' => 1024,
            'not null' => FALSE,
          ),
          'width' => array(
            'description' => 'The width of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
          'height' => array(
            'description' => 'The height of the image in pixels.',
            'type' => 'int',
            'unsigned' => TRUE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
      'field_rendered_map' => array(
        'translatable' => '0',
        'entity_types' => array(),
        'settings' => array(),
        'storage' => array(
          'type' => 'field_sql_storage',
          'settings' => array(),
          'module' => 'field_sql_storage',
          'active' => '1',
          'details' => array(
            'sql' => array(
              'FIELD_LOAD_CURRENT' => array(
                'field_data_field_rendered_map' => array(
                  'value' => 'field_rendered_map_value',
                  'format' => 'field_rendered_map_format',
                ),
              ),
              'FIELD_LOAD_REVISION' => array(
                'field_revision_field_rendered_map' => array(
                  'value' => 'field_rendered_map_value',
                  'format' => 'field_rendered_map_format',
                ),
              ),
            ),
          ),
        ),
        'foreign keys' => array(
          'format' => array(
            'table' => 'filter_format',
            'columns' => array(
              'format' => 'format',
            ),
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'field_name' => 'field_rendered_map',
        'type' => 'text_long',
        'module' => 'text',
        'active' => '1',
        'locked' => '0',
        'cardinality' => '1',
        'deleted' => '0',
        'columns' => array(
          'value' => array(
            'type' => 'text',
            'size' => 'big',
            'not null' => FALSE,
          ),
          'format' => array(
            'type' => 'varchar',
            'length' => 255,
            'not null' => FALSE,
          ),
        ),
        'bundles' => array(
          'node' => array(
            0 => 'asu_event',
          ),
        ),
      ),
    ),

    'instances' => array(
      // @TODO - ASU Social Share - reuse?
      // 'field_asu_social_share' => array(
      //   0 => array(
      //     'default_value' => NULL,
      //     'description' => '',
      //     'display' => array(
      //       'default' => array(
      //         'label' => 'above',
      //         'module' => 'gigya',
      //         'settings' => array(
      //           'gigya_sharebar_advanced' => array(),
      //           'gigya_sharebar_buttons' => 'facebook, twitter-tweet, google-plusone, pinterest, linkedin, email, share',
      //           'gigya_sharebar_container_id' => 'gigya-share',
      //           'gigya_sharebar_desc' => '[node:summary]',
      //           'gigya_sharebar_image_behavior' => 'default',
      //           'gigya_sharebar_image_url' => '',
      //           'gigya_sharebar_layout' => 'horizontal',
      //           'gigya_sharebar_link_back' => '[node:url:absolute]',
      //           'gigya_sharebar_override_default' => FALSE,
      //           'gigya_sharebar_short_url' => 1,
      //           'gigya_sharebar_showcounts' => 'none',
      //           'gigya_sharebar_title' => '[node:title]',
      //         ),
      //         'type' => 'gigya_sharebar_formatter_default',
      //         'weight' => 49,
      //       ),
      //     )+$display_arr,
      //     'label' => 'Social Share',
      //     'required' => FALSE,
      //     'settings' => array(
      //       'user_register_form' => FALSE,
      //     ),
      //     'widget' => array(
      //       'active' => 0,
      //       'module' => 'gigya',
      //       'settings' => array(),
      //       'type' => 'gigya_sharebar',
      //       'weight' => '51',
      //     ),
      //     'field_name' => 'field_asu_social_share',
      //     'entity_type' => 'node',
      //     'bundle' => 'asu_event',
      //     'deleted' => '0',
      //   ),
      // ),
      'field_asuevent_artists' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '21',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '16',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '36',
            ),
          )+$display_arr,
          'label' => 'Artists',
          'required' => FALSE,
          'settings' => array(
            'text_processing' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'module' => 'text',
            'settings' => array(
              'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => '24',
          ),
          'field_name' => 'field_asuevent_artists',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_campus' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '12',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '9',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '23',
            ),
          )+$display_arr,
          'label' => 'Campus',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '14',
          ),
          'field_name' => 'field_asuevent_campus',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_closing_recep' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '24',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '18',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '35',
            ),
          )+$display_arr,
          'label' => 'Closing Reception',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '27',
          ),
          'field_name' => 'field_asuevent_closing_recep',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_contact_name' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '26',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '21',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '21',
            ),
          )+$display_arr,
          'label' => 'Contact',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '29',
          ),
          'field_name' => 'field_asuevent_contact_name',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_curator' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '22',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '19',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '33',
            ),
          )+$display_arr,
          'label' => 'Curator',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '25',
          ),
          'field_name' => 'field_asuevent_curator',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_date' => array(
        0 => array(
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'date',
              'settings' => array(
                'format_type' => 'long',
                'fromto' => 'both',
                'multiple_from' => '',
                'multiple_number' => '',
                'multiple_to' => '',
              ),
              'type' => 'date_default',
              'weight' => '42',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '25',
            ),
          )+$display_arr,
          'label' => 'Date (ISO format)',
          'required' => 0,
          'settings' => array(
            'default_value' => 'now',
            'default_value2' => 'same',
            'default_value_code' => '',
            'default_value_code2' => '',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'date',
            'settings' => array(
              'display_all_day' => 0,
              'increment' => 15,
              'input_format' => 'm/d/Y - H:i:s',
              'input_format_custom' => '',
              'label_position' => 'above',
              'text_parts' => array(),
              'year_range' => '-3:+3',
            ),
            'type' => 'date_text',
            'weight' => '43',
          ),
          'field_name' => 'field_asuevent_date',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_dept' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '16',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '5',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '26',
            ),
          )+$display_arr,
          'label' => 'Department',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '18',
          ),
          'field_name' => 'field_asuevent_dept',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_display_date' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '4',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '1',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '28',
            ),
          )+$display_arr,
          'label' => 'Display Date (Text)',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '6',
          ),
          'field_name' => 'field_asuevent_display_date',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_email' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '19',
            ),
            'full' => array(
              'label' => 'inline',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '29',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '32',
            ),
          )+$display_arr,
          'label' => 'Email',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '21',
          ),
          'field_name' => 'field_asuevent_email',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_email2' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'email',
              'settings' => array(),
              'type' => 'email_default',
              'weight' => 46,
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => 0,
            ),
            'teaser' => array(
              'label' => 'above',
              'type' => 'hidden',
              'weight' => '0',
              'settings' => array(),
            ),
          )+$display_arr,
          'label' => 'Email',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'email',
            'settings' => array(
              'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
              'size' => 60,
            ),
            'type' => 'email_textfield',
            'weight' => '47',
          ),
          'field_name' => 'field_asuevent_email2',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_email_view' => array(
        0 => array(
          'default_value' => array(
            0 => array(
              'vname' => 'asu_event_images|block_2',
              'vargs' => '[node:nid]',
            ),
          ),
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'viewfield',
              'settings' => array(),
              'type' => 'viewfield_default',
              'weight' => '41',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'viewfield',
              'settings' => array(),
              'type' => 'viewfield_default',
              'weight' => '22',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '15',
            ),
          )+$display_arr,
          'ds_extras_field_template' => '',
          'label' => 'Email',
          'required' => 0,
          'settings' => array(
            'allowed_views' => array(
              'asu_event_images' => 'asu_event_images',
              'events' => 0,
              'feeds_log' => 0,
            ),
            'force_default' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'viewfield',
            'settings' => array(),
            'type' => 'viewfield_select',
            'weight' => '22',
          ),
          'field_name' => 'field_asuevent_email_view',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_image' => array(
        0 => array(
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'image',
              'settings' => array(
                'image_link' => '',
                'image_style' => '',
              ),
              'type' => 'image',
              'weight' => '43',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '26',
            ),
          )+$display_arr,
          'label' => 'Image',
          'required' => 0,
          'settings' => array(
            'alt_field' => 0,
            'default_image' => 0,
            'file_directory' => 'images_asuevents',
            'file_extensions' => 'png gif jpg jpeg',
            'max_filesize' => '',
            'max_resolution' => '',
            'min_resolution' => '',
            'title_field' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'image',
            'settings' => array(
              'preview_image_style' => 'thumbnail',
              'progress_indicator' => 'throbber',
              'manualcrop_enable' => FALSE,
              'manualcrop_keyboard' => TRUE,
              'manualcrop_thumblist' => FALSE,
              'manualcrop_inline_crop' => FALSE,
              'manualcrop_crop_info' => TRUE,
              'manualcrop_instant_preview' => TRUE,
              'manualcrop_instant_crop' => FALSE,
              'manualcrop_default_crop_area' => TRUE,
              'manualcrop_maximize_default_crop_area' => FALSE,
              'manualcrop_styles_mode' => 'include',
              'manualcrop_styles_list' => array(),
              'manualcrop_require_cropping' => array(),
            ),
            'type' => 'image_image',
            'weight' => '44',
          ),
          'field_name' => 'field_asuevent_image',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_image_view' => array(
        0 => array(
          'default_value' => array(
            0 => array(
              'vname' => 'asu_event_images|block_1',
              'vargs' => '[node:nid]',
            ),
          ),
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'viewfield',
              'settings' => array(),
              'type' => 'viewfield_default',
              'weight' => '40',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'viewfield',
              'settings' => array(),
              'type' => 'viewfield_default',
              'weight' => '11',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '14',
            ),
          )+$display_arr,
          'ds_extras_field_template' => '',
          'label' => 'Event image view',
          'required' => 0,
          'settings' => array(
            'allowed_views' => array(
              'academic_units' => 0,
              'asu_eadvisor_degree' => 0,
              'asu_eadvisor_degree_new' => 0,
              'asu_event_images' => 'asu_event_images',
              'asu_news_main_images' => 0,
              'calendar' => 0,
              'events' => 0,
              'faculty_and_staff' => 0,
              'feature_box' => 0,
              'feeds_log' => 0,
              'news_and_events_highlights' => 0,
              'news_and_events_slideshow' => 0,
              'nodequeue_1' => 0,
              'nodequeue_2' => 0,
              'nodequeue_3' => 0,
              'nodequeue_4' => 0,
              'test' => 0,
            ),
            'force_default' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'viewfield',
            'settings' => array(),
            'type' => 'viewfield_select',
            'weight' => '11',
          ),
          'field_name' => 'field_asuevent_image_view',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_img_alt' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '44',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '27',
            ),
          )+$display_arr,
          'label' => 'Image alt',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '45',
          ),
          'field_name' => 'field_asuevent_img_alt',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_img_caption' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '45',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '28',
            ),
          )+$display_arr,
          'label' => 'Image caption',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'rows' => '5',
            ),
            'type' => 'text_textarea',
            'weight' => '46',
          ),
          'field_name' => 'field_asuevent_img_caption',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_location' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '11',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '7',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '27',
            ),
          )+$display_arr,
          'label' => 'Location',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '13',
          ),
          'field_name' => 'field_asuevent_location',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_more_info' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '29',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '24',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '38',
            ),
          )+$display_arr,
          'label' => 'Website',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '32',
          ),
          'field_name' => 'field_asuevent_more_info',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_nid' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'number',
              'settings' => array(
                'decimal_separator' => '.',
                'prefix_suffix' => 1,
                'scale' => 0,
                'thousand_separator' => '',
              ),
              'type' => 'number_integer',
              'weight' => '0',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '35',
            ),
            'ical' => array(
              'label' => 'above',
              'module' => 'number',
              'settings' => array(
                'decimal_separator' => '.',
                'prefix_suffix' => TRUE,
                'scale' => 0,
                'thousand_separator' => ' ',
              ),
              'type' => 'number_integer',
              'weight' => '0',
            ),
          )+$display_arr,
          'label' => 'Nid at ASU Events site',
          'required' => 0,
          'settings' => array(
            'max' => '',
            'min' => '',
            'prefix' => '',
            'suffix' => '',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'number',
            'settings' => array(),
            'type' => 'number',
            'weight' => '0',
          ),
          'field_name' => 'field_asuevent_nid',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_nonacademic_unit' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '15',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '4',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '4',
            ),
          )+$display_arr,
          'label' => 'Non academic units',
          'required' => FALSE,
          'settings' => array(
            'text_processing' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'module' => 'text',
            'settings' => array(
              'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => '17',
          ),
          'field_name' => 'field_asuevent_nonacademic_unit',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_opening_recep' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '23',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '17',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '34',
            ),
          )+$display_arr,
          'label' => 'Opening Reception',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '26',
          ),
          'field_name' => 'field_asuevent_opening_recep',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_other_dept' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '17',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '6',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '7',
            ),
          )+$display_arr,
          'label' => 'Other department',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '19',
          ),
          'field_name' => 'field_asuevent_other_dept',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_past_exhibitions' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '25',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '20',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '22',
            ),
          )+$display_arr,
          'label' => 'Past Exhibitions',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'rows' => '5',
            ),
            'type' => 'text_textarea',
            'weight' => '28',
          ),
          'field_name' => 'field_asuevent_past_exhibitions',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_pdf' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '27',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '13',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '20',
            ),
          )+$display_arr,
          'label' => 'PDF',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '31',
          ),
          'field_name' => 'field_asuevent_pdf',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_phone' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '18',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '23',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '31',
            ),
          )+$display_arr,
          'label' => 'Phone',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '20',
          ),
          'field_name' => 'field_asuevent_phone',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_press_release' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '28',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '21',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '8',
            ),
          )+$display_arr,
          'label' => 'Press release',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '30',
          ),
          'field_name' => 'field_asuevent_press_release',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_price' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '10',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '10',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '24',
            ),
          )+$display_arr,
          'label' => 'Price',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '12',
          ),
          'field_name' => 'field_asuevent_price',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_register_other' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '34',
            ),
            'full' => array(
              'label' => 'inline',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '24',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '3',
            ),
          )+$display_arr,
          'label' => 'Registration other',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '37',
          ),
          'field_name' => 'field_asuevent_register_other',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_registration_url' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '33',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '27',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '2',
            ),
          )+$display_arr,
          'label' => 'Registration',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '36',
          ),
          'field_name' => 'field_asuevent_registration_url',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_room' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '13',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '8',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '40',
            ),
          )+$display_arr,
          'label' => 'Room',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '15',
          ),
          'field_name' => 'field_asuevent_room',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_rsvp_other' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '32',
            ),
            'full' => array(
              'label' => 'inline',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '23',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '1',
            ),
          )+$display_arr,
          'label' => 'RSVP other',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '35',
          ),
          'field_name' => 'field_asuevent_rsvp_other',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_rsvp_url' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '31',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '26',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '5',
            ),
          )+$display_arr,
          'label' => 'RSVP',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '34',
          ),
          'field_name' => 'field_asuevent_rsvp_url',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_sponsorship' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '20',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '2',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '37',
            ),
          )+$display_arr,
          'label' => 'Sponsorship',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '23',
          ),
          'field_name' => 'field_asuevent_sponsorship',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_subtitle' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '6',
            ),
            'full' => array(
              'label' => 'hidden',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '0',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '30',
            ),
          )+$display_arr,
          'label' => 'Subtitle',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '60',
            ),
            'type' => 'text_textfield',
            'weight' => '4',
          ),
          'field_name' => 'field_asuevent_subtitle',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_tax_audience' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => '39',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '33',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '13',
            ),
          )+$display_arr,
          'ds_extras_field_template' => '',
          'label' => 'Taxonomy: ASU Events Audience',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '42',
          ),
          'field_name' => 'field_asuevent_tax_audience',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_tax_category' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => '35',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '31',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '10',
            ),
          )+$display_arr,
          'label' => 'Taxonomy: ASU Events Category',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '38',
          ),
          'field_name' => 'field_asuevent_tax_category',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_tax_type' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => '37',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '32',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '18',
            ),
          )+$display_arr,
          'label' => 'Taxonomy: ASU Events Type',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '40',
          ),
          'field_name' => 'field_asuevent_tax_type',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_thumb_img' => array(
        0 => array(
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'image',
              'settings' => array(
                'image_link' => '',
                'image_style' => 'news_events_thumb_image_style',
              ),
              'type' => 'image',
              'weight' => '8',
            ),
            'full' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '36',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '29',
            ),
          )+$display_arr,
          'label' => 'Thumbnail image',
          'required' => 0,
          'settings' => array(
            'alt_field' => 0,
            'default_image' => 0,
            'file_directory' => 'images_asuevents',
            'file_extensions' => 'png gif jpg jpeg',
            'max_filesize' => '',
            'max_resolution' => '',
            'min_resolution' => '',
            'title_field' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'image',
            'settings' => array(
              'filefield_sources' => array(
                'filefield_sources' => array(
                  'attach' => 0,
                  'reference' => 0,
                  'remote' => 'remote',
                ),
                'source_attach' => array(
                  'absolute' => '0',
                  'attach_mode' => 'copy',
                  'path' => 'file_attach',
                ),
                'source_reference' => array(
                  'autocomplete' => '0',
                ),
              ),
              'insert' => 0,
              'insert_class' => '',
              'insert_default' => 'auto',
              'insert_styles' => array(
                'auto' => 'auto',
                'image' => 0,
                'image_academic_unit_image_style' => 0,
                'image_featuer_box_teaser_image_style' => 0,
                'image_featured_item_image_style' => 0,
                'image_landing_page_image_style' => 0,
                'image_large' => 0,
                'image_medium' => 0,
                'image_news_events_slideshow_image_style' => 0,
                'image_news_events_slideshow_temp_style' => 0,
                'image_thumbnail' => 0,
                'link' => 0,
              ),
              'insert_width' => '',
              'preview_image_style' => 'thumbnail',
              'progress_indicator' => 'throbber',
              'manualcrop_enable' => FALSE,
              'manualcrop_keyboard' => TRUE,
              'manualcrop_thumblist' => FALSE,
              'manualcrop_inline_crop' => FALSE,
              'manualcrop_crop_info' => TRUE,
              'manualcrop_instant_preview' => TRUE,
              'manualcrop_instant_crop' => FALSE,
              'manualcrop_default_crop_area' => TRUE,
              'manualcrop_maximize_default_crop_area' => FALSE,
              'manualcrop_styles_mode' => 'include',
              'manualcrop_styles_list' => array(),
              'manualcrop_require_cropping' => array(),
            ),
            'type' => 'image_image',
            'weight' => '9',
          ),
          'field_name' => 'field_asuevent_thumb_img',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_ticketing_url' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '30',
            ),
            'full' => array(
              'label' => 'inline',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '25',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '6',
            )+$display_arr,
          ),
          'label' => 'Ticketing',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '33',
          ),
          'field_name' => 'field_asuevent_ticketing_url',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_unit' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'text',
              'settings' => array(),
              'type' => 'text_default',
              'weight' => '14',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '25',
            ),
          )+$display_arr,
          'label' => 'Unit',
          'required' => 0,
          'settings' => array(
            'text_processing' => '0',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
              'size' => '120',
            ),
            'type' => 'text_textfield',
            'weight' => '16',
          ),
          'field_name' => 'field_asuevent_unit',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_url' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => '1',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '39',
            ),
          )+$display_arr,
          'label' => 'URL at ASU Events site',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => 'default',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => '80',
            ),
            'enable_tokens' => 1,
            'title' => 'optional',
            'title_maxlength' => '128',
            'title_value' => '',
            'url' => 0,
            'user_register_form' => FALSE,
            'validate_url' => 1,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '1',
          ),
          'field_name' => 'field_asuevent_url',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_asuevent_very_start_date' => array(
        0 => array(
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'date',
              'settings' => array(
                'format_type' => 'long',
                'fromto' => 'both',
                'multiple_from' => '',
                'multiple_number' => '',
                'multiple_to' => '',
              ),
              'type' => 'date_default',
              'weight' => '5',
            ),
            'ical' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => '17',
            ),
          )+$display_arr,
          'ds_extras_field_template' => '',
          'label' => 'Very start and end date',
          'required' => 0,
          'settings' => array(
            'default_value' => 'now',
            'default_value2' => 'same',
            'default_value_code' => '',
            'default_value_code2' => '',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'date',
            'settings' => array(
              'display_all_day' => 0,
              'increment' => 15,
              'input_format' => 'm/d/Y - g:i:sa',
              'input_format_custom' => '',
              'label_position' => 'above',
              'repeat_collapsed' => 0,
              'text_parts' => array(),
              'year_range' => '-3:+3',
            ),
            'type' => 'date_text',
            'weight' => '7',
          ),
          'field_name' => 'field_asuevent_very_start_date',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_college_unit' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => 50,
            ),
          )+$display_arr,
          'label' => 'College Unit',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '53',
          ),
          'field_name' => 'field_college_unit',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_constituent_type' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => 53,
            ),
          )+$display_arr,
          'label' => 'Constituent Type',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '58',
          ),
          'field_name' => 'field_constituent_type',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_event_location' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'link',
              'settings' => array(),
              'type' => 'link_default',
              'weight' => 55,
            ),
          )+$display_arr,
          'label' => 'Event Location',
          'required' => 0,
          'settings' => array(
            'attributes' => array(
              'class' => '',
              'configurable_title' => 0,
              'rel' => '',
              'target' => '_blank',
              'title' => '',
            ),
            'display' => array(
              'url_cutoff' => 80,
            ),
            'enable_tokens' => 1,
            'linkit' => array(
              'button_text' => 'Search',
              'enable' => 0,
              'profile' => '',
            ),
            'rel_remove' => 'default',
            'title' => 'optional',
            'title_maxlength' => 255,
            'title_value' => '',
            'url' => 'optional',
            'user_register_form' => FALSE,
            'validate_url' => 0,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => '61',
          ),
          'field_name' => 'field_event_location',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_event_map' => array(
        0 => array(
          'default_value' => array(
            0 => array(
              'campus_selection' => 'TEMPE',
              'enhanced_map_height' => '650',
              'display_campus_select' => 'NO',
              'bird_fieldset' => array(
                'top_category_id' => array(
                  6396 => 0,
                  10980 => 0,
                  11356 => 0,
                  12477 => 0,
                  6268 => 0,
                  10357 => 0,
                  8599 => 0,
                  12396 => 0,
                  9284 => 0,
                  11383 => 0,
                  6267 => 0,
                  6277 => 0,
                  7249 => 0,
                  6315 => 0,
                  6292 => 0,
                  12569 => 0,
                  10599 => 0,
                ),
                'sub_category' => array(),
                'location_id' => array(),
              ),
              'map_items' => '[{"campus":"TEMPE","name":"maps_enhanced_settings","map_height":650,"display_campus_select":"NO"}]',
              'description' => '',
            ),
          ),
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'asu_maps_enhanced',
              'settings' => array(),
              'type' => 'asu_maps_enhanced',
              'weight' => 47,
            ),
          )+$display_arr,
          'label' => 'Event Map',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'weight' => '48',
            'type' => 'asu_maps_enhanced_form',
            'module' => 'asu_maps_enhanced',
            'active' => 0,
            'settings' => array(),
          ),
          'field_name' => 'field_event_map',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_event_type' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => 52,
            ),
          )+$display_arr,
          'label' => 'Event type',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '56',
          ),
          'field_name' => 'field_event_type',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_interests' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => 54,
            ),
          )+$display_arr,
          'label' => 'Interests',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '60',
          ),
          'field_name' => 'field_interests',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_locations' => array(
        0 => array(
          'default_value' => NULL,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'taxonomy',
              'settings' => array(),
              'type' => 'taxonomy_term_reference_link',
              'weight' => 51,
            ),
          )+$display_arr,
          'label' => 'Locations',
          'required' => 0,
          'settings' => array(
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'taxonomy',
            'settings' => array(
              'autocomplete_path' => 'taxonomy/autocomplete',
              'size' => 60,
            ),
            'type' => 'taxonomy_autocomplete',
            'weight' => '55',
          ),
          'field_name' => 'field_locations',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_news_events_thumb_img' => array(
        0 => array(
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'image',
              'settings' => array(
                'image_link' => '',
                'image_style' => 'news_events_thumb_image_style',
              ),
              'type' => 'image',
              'weight' => '7',
            ),
          )+$display_arr,
          'label' => 'Thumb image (Used in Highlights)',
          'required' => 0,
          'settings' => array(
            'alt_field' => 0,
            'default_image' => 0,
            'file_directory' => 'images_asuevents',
            'file_extensions' => 'png gif jpg jpeg',
            'max_filesize' => '',
            'max_resolution' => '',
            'min_resolution' => '',
            'title_field' => 0,
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'image',
            'settings' => array(
              'filefield_sources' => array(
                'filefield_sources' => array(
                  'attach' => 0,
                  'reference' => 0,
                  'remote' => 'remote',
                ),
                'source_attach' => array(
                  'absolute' => '0',
                  'attach_mode' => 'copy',
                  'path' => 'file_attach',
                ),
                'source_reference' => array(
                  'autocomplete' => '0',
                ),
              ),
              'insert' => 0,
              'insert_class' => '',
              'insert_default' => 'auto',
              'insert_styles' => array(
                'auto' => 'auto',
                'image' => 0,
                'image_academic_unit_image_style' => 0,
                'image_asuevent_image_style' => 0,
                'image_featuer_box_teaser_image_style' => 0,
                'image_featured_item_image_style' => 0,
                'image_landing_page_image_style' => 0,
                'image_large' => 0,
                'image_medium' => 0,
                'image_news_events_slideshow_image_style' => 0,
                'image_news_events_slideshow_temp_style' => 0,
                'image_news_events_thumb_image_style' => 0,
                'image_thumbnail' => 0,
                'link' => 0,
              ),
              'insert_width' => '',
              'preview_image_style' => 'news_events_thumb_image_style',
              'progress_indicator' => 'throbber',
              'manualcrop_enable' => FALSE,
              'manualcrop_keyboard' => TRUE,
              'manualcrop_thumblist' => FALSE,
              'manualcrop_inline_crop' => FALSE,
              'manualcrop_crop_info' => TRUE,
              'manualcrop_instant_preview' => TRUE,
              'manualcrop_instant_crop' => FALSE,
              'manualcrop_default_crop_area' => TRUE,
              'manualcrop_maximize_default_crop_area' => FALSE,
              'manualcrop_styles_mode' => 'include',
              'manualcrop_styles_list' => array(),
              'manualcrop_require_cropping' => array(),
            ),
            'type' => 'image_image',
            'weight' => '8',
          ),
          'field_name' => 'field_news_events_thumb_img',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
      'field_rendered_map' => array(
        0 => array(
          'label' => 'Rendered Map',
          'widget' => array(
            'weight' => '62',
            'type' => 'text_textarea',
            'module' => 'text',
            'active' => 1,
            'settings' => array(
              'rows' => '5',
              'maxlength_js' => '',
              'maxlength_js_enforce' => 0,
              'maxlength_js_truncate_html' => 0,
              'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
            ),
          ),
          'settings' => array(
            'text_processing' => '0',
            'linkit' => array(
              'enable' => 0,
              'profile' => '',
              'button_text' => 'Search',
            ),
            'user_register_form' => FALSE,
          ),
          'display' => array(
            'default' => array(
              'label' => 'above',
              'type' => 'text_default',
              'settings' => array(),
              'module' => 'text',
              'weight' => 56,
            ),
          )+$display_arr,
          'required' => 0,
          'description' => '',
          'default_value' => NULL,
          'field_name' => 'field_rendered_map',
          'entity_type' => 'node',
          'bundle' => 'asu_event',
          'deleted' => '0',
        ),
      ),
    ),
  );

  _asu_events_create_fields_helper($data);
}

function _asu_events_create_fields_helper($data) {
  // Create or update fields and their instances
  if (isset($data['fields'])) {
    $modules = module_list();
    foreach ($data['fields'] as $key => $field) {
      // Check if the field module exists.
      $module = $field['module'];
      if (!isset($modules[$module])) {
        drupal_set_message(t('%field_name field could not be created because the module %module is disabled or missing.', array('%field_name' => $key, '%module' => $module)), 'error');
        continue;
      }

      if (isset($data['instances'][$key])) {

        // Create or update field.
        $prior_field = field_info_field($field['field_name']);
        //drupal_set_message(t('%field_name field is being checked.', array('%field_name' => $key)), 'status');
        if (!$prior_field) {
          try {
            //drupal_set_message(t('%field_name field is being created.', array('%field_name' => $key)), 'status');
            field_create_field($field);
            //drupal_set_message(t('%field_name field has been created.', array('%field_name' => $key)), 'status');
          }
          catch (ErrorException $e){
            drupal_set_message(t('Error creating %field_name', array('%field_name' => $key)), 'status');
          }

        }
        else {
          $field['id'] = $prior_field['id'];
          //drupal_set_message(t('%field_name field is being updated.', array('%field_name' => $key)), 'status');
          //field_update_field($field);
          //drupal_set_message(t('%field_name field has been updated.', array('%field_name' => $key)), 'status');
        }

        // Create or update field instances.
        foreach ($data['instances'][$key] as $ikey => $instance) {

          // Make sure the needed key exists.
          if (!isset($instance['field_name'])) {
            continue;
          }

          $prior_instance = field_read_instance($instance['entity_type'], $instance['field_name'], $instance['bundle']);
          if (!$prior_instance) {
            field_create_instance($instance);
            //drupal_set_message(t('%field_name instance has been created for @bundle in @entity_type.', array('%field_name' => $key, '@bundle' => $instance['bundle'], '@entity_type' => $instance['entity_type'])));
          }
          else {
            $instance['id'] = $prior_instance['id'];
            $instance['field_id'] = $prior_instance['field_id'];
            field_update_instance($instance);
            //drupal_set_message(t('%field_name instance has been updated for @bundle in @entity_type.', array('%field_name' => $key, '@bundle' => $instance['bundle'], '@entity_type' => $instance['entity_type'])));
          }
        }
      }
    }
  }
}


/**
 * Implements hook_update_N().
 * + Disable deprecated experimental modules
 * @param $sandbox
 */
function asu_events_update_7003(&$sandbox) {
    module_disable(array('asu_events'));
    drupal_uninstall_modules(array('asu_events'));
}