<?php
/**
 * @file
 * Code for the ASU Academic Programs Feature feature.
 */

include_once 'asu_ap_feature.features.inc';

/**
 *  Implements hook_form_alter().
 */
function asu_ap_feature_form_alter(&$form, &$form_state, $form_id) {

  // Hide irrelavant fields on ASU Academic Programs node edit form
  if ($form_id == 'asu_ap_node_form') {
    $form['some_text'] = array('#markup' => '<div class="messages warning">If information needs to be changed, please do so on the degree catalog by contacting the Provost\'s Office.</div>');
    $form['body']['#access'] = FALSE;
    $form['field_asu_ap_acad_plan']['#access'] = FALSE;
    $form['field_asu_ap_acad_prog']['#access'] = FALSE;
    $form['field_asu_ap_college']['#access'] = FALSE;
    $form['field_asu_ap_college_url']['#access'] = FALSE;
    $form['field_asu_ap']['#access'] = FALSE;
    $form['field_asu_ap_admission_req']['#access'] = FALSE;
    $form['field_asu_ap_prog_req']['#access'] = FALSE;
    $form['field_asu_ap_asuds_url']['#access'] = FALSE;
    $form['field_asu_ap_awarded']['#access'] = FALSE;
    $form['field_asu_ap_campus']['#access'] = FALSE;
    $form['field_asu_ap_career_opps']['#access'] = FALSE;
    $form['field_asu_ap_cert']['#access'] = FALSE;
    $form['field_asu_ap_department']['#access'] = FALSE;
    $form['field_asu_ap_department_code']['#access'] = FALSE;
    $form['field_asu_ap_example_careers']['#access'] = FALSE;
    $form['field_asu_ap_major_map_url']['#access'] = FALSE;
    $form['field_asu_ap_major_map_year']['#access'] = FALSE;
    $form['field_asu_ap_min_math']['#access'] = FALSE;
    $form['field_asu_ap_program']['#access'] = FALSE;
    $form['field_asu_ap_program_fee']['#access'] = FALSE;
    $form['field_asu_ap_req_desc']['#access'] = FALSE;
    $form['field_asu_ap_second_language']['#access'] = FALSE;
    $form['field_asu_ap_subplan_title']['#access'] = FALSE;
    $form['field_asu_ap_subplan_url']['#access'] = FALSE;
    $form['field_asu_ap_diploma_desc']['#access'] = FALSE;

    if ($form['field_asu_ap_program']['und'][0]['value']['#default_value'] == 'undergrad') {
        $form['field_asu_ap_grad_app']['#access'] = FALSE;
        $form['field_asu_ap_grad_financing']['#access'] = FALSE;
        $form['field_asu_ap_grad_desc_video']['#access'] = FALSE;
        $form['field_asu_ap_grad_text_area']['#access'] = FALSE;
        if (($form['field_asu_ap']['und'][0]['value']['#default_value'] == 'Minor') || ($form['field_asu_ap']['und'][0]['value']['#default_value'] == 'Certificate')) {
            $form['field_asu_ap_career_outlook']['#access'] = FALSE;
            $form['field_asu_ap_ex_car_tf']['#access'] = FALSE;
        }
    } else if ($form['field_asu_ap_program']['und'][0]['value']['#default_value'] == 'graduate') {
        $form['field_asu_ap_addl_req']['#access'] = FALSE;
        $form['field_asu_ap_sl']['#access'] = FALSE;
        $form['field_asu_ap_wue_available']['#access'] = FALSE;
        $form['field_asu_ap_career_outlook']['#access'] = FALSE;
        $form['field_asu_ap_ex_car_tf']['#access'] = FALSE;
    }

  }
}

/**
 * Implements hook_field_default_field_instances_alter().
 *
 * Set the default image.
 */
function asu_ap_feature_field_default_field_instances_alter(&$fields) {
  if (isset($fields['node-asu_ap-field_asu_banner_image']['settings']['default_image'])) {
    $fields['node-asu_ap-field_asu_banner_image']['settings']['default_image'] = variable_get('asu_ap_feature_banner_fid');
  }
  if (isset($fields['node-asu_ap-field_degree_image']['settings']['default_image'])) {
    $fields['node-asu_ap-field_degree_image']['settings']['default_image'] = variable_get('asu_ap_feature_image_fid');
  }
}

  /**
   * Grab image within the Feature module. Then, create image in the new site to use for default image for the ASU Academic Programs Banner Image field.
	 */
function _asu_ap_feature_image($image, $key) {
  $filename = $image;
  $origfile = drupal_get_path('module', 'asu_ap_feature') . '/images/' . $filename;
  $uri = 'public://' . $filename;
  $file = (object) array(
    'uid' => 1,
    'filename' => $filename,
    'uri' => $origfile,
    'filemime' => 'image/jpg',
    'filesize' => filesize($origfile),
    'status' => FILE_STATUS_PERMANENT,
  );
  $file = file_copy($file, $uri, FILE_EXISTS_REPLACE);
  variable_set('asu_ap_feature_' . $key . '_fid', $file->fid);
}
