<?php

//include_once('asu_spotlight.features.inc');
include_once('asu_spotlight.spotlight.inc');

function asu_spotlight_menu_alter(&$items) {
    $items['admin/config/media/flexslider']['title'] = 'ASU Spotlight';
}

/**
 * Implementation of hook_entity_info_alter()
 */
function asu_spotlight_entity_info_alter(&$entity_info) {


  // Spotlight
  $entity_info['fieldable_panels_pane']['bundles']['asu_spotlight'] = array(
    'label' => t('Add ASU spotlight'),
    'description' => t('Add ASU spotlight'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_spotlight.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/asu_spotlight',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


function asu_spotlight_theme() {
  return array(
    // ASU flexslider container
    'asu_spotlight' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'template' => 'theme/asu_spotlight',
      'file' => 'theme/asu_spotlight.theme.inc',
    ),

    // Slide container
    'asu_spotlight_list' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'file' => 'theme/asu_spotlight.theme.inc',
    ),

    // Slide item
    'asu_spotlight_list_item' => array(
      'variables' => array('item' => array(), 'settings' => array(), 'caption' => ''),
      'file' => 'theme/asu_spotlight.theme.inc',
    ),
  );
}
