<?php
/**
 * @file
 *   Utilizes Feeds module architecture to import and process feeds.
 */
/**
 * Implementation of hook_feeds_plugins().
 */
function asu_feeds2_feeds_plugins() {
  $info = array();
  $info['ASUeAdvisorFeedParser'] = array(
    'name' => t('ASU eAdvisor Feed Parser'),
    'description' => t('Parse ASU eAdvisor degree data.'),
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'ASUeAdvisorFeedParser',
      'file' => 'ASUeAdvisorFeedParser.inc',
      'path' => drupal_get_path('module', 'asu_feeds2') . '/includes/',
    ),
  );
  $info['ASUeAdvisorFeedFetcher'] = array(
    'name' => t('ASU eAdvisor Feed Fetcher'),
    'description' => t('Fetcher for ASU eAdvisor degree data, via XML-RPC using the IXR library.'),
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'ASUeAdvisorFeedFetcher',
      'file' => 'ASUeAdvisorFeedFetcher.inc',
      'path' => drupal_get_path('module', 'asu_feeds2') . '/includes/',
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function asu_feeds2_enable() {
  //clear the cache to display in Feeds as available plugin.
	drupal_flush_all_caches();
}

/**
 * Implements hook_theme().
 */
function asu_feeds2_theme($existing, $type, $theme, $path) {
  return array(
    // Theme function used by custom field formatter for Example Careers.
    'asu_feeds2_example_career_table' => array(
      'variables' => array(
        'element' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function asu_feeds2_field_formatter_info() {
  // Define custom field formatter.
  return array(
    'asu_feeds2_example_career_table' => array(
      'label' => t('ASU Feeds Example Careers Field Formatter'),
      'field types' => array('text_long'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Lines up theme function to use, and calls it.
 */
function asu_feeds2_field_formatter_view($entity_type, $entity, $field, $instance, $lang_code, $items, $display) {
  $element = array();
  $theme_function = $display['type'];

  foreach ($items as $delta => $item) {
    $element[$delta] = array(
      '#markup' => theme($theme_function, array('element' => $item)),
    );
  }
  return $element;
}

/**
 * Theme function for asu_feeds Example Careers formatter.
 *
 * @param array $vars
 *
 * @return string Rendered output.
 */
function theme_asu_feeds2_example_career_table($vars) {

  drupal_add_css(drupal_get_path('module', 'asu_feeds2') . '/css/asu_feeds2.css');

  $header = array('Career', '*growth', '*median salary');
  $rows = array();

  // Convert the stored JSON array into a PHP array.
  $dataset = json_decode($vars['element']['value']);

  // Build rows.
  foreach ($dataset as $career) {
    // Career
    $career->careerDataOnetTitle = isset($career->careerDataOnetTitle) ? $career->careerDataOnetTitle : '';
    // Bright (metadata)
    $bright = '';
    if (isset($career->careerDataBrightOutlook) && ($career->careerDataBrightOutlook == "BRIGHT")) {
      $bright = ' <i class="fa fa-sun-o text-yellow"></i>';
    }
    // Green (metadata)
    $green = '';
    if (isset($career->careerDataGreen) && ($career->careerDataGreen == "GREEN")) {
      $green = ' <i class="fa fa-leaf text-green"></i>';
    }
    // Growth
    $career->careerDataGrowth = isset($career->careerDataGrowth) ? $career->careerDataGrowth . '%' : '';
    // Salary
    $career->careerDataSalary = isset($career->careerDataSalary) ? $career->careerDataSalary : '';

    // Assign the row data.
    $rows[] = array(
      array('data' => $career->careerDataOnetTitle . $bright . $green , 'align' => 'left'),
      array('data' => $career->careerDataGrowth, 'align' => 'left'),
      array('data' => $career->careerDataSalary, 'align' => 'left'),
    );

  }

  // Create a Drupal table render array.
  $output[] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#attributes' => array('class' => array('table-class responsive-table')),
    '#empty' =>t('Your table is empty'),
  );
  return '<p>Students who complete this degree program may be prepared for the following careers. Advanced degrees or certifications may be required for academic or clinical positions. Career examples include but are not limited to:</p><br>' . drupal_render($output) . '<br><p class="asu-degrees-example-careers-small">* Data obtained from the Occupational Information Network (O*NET) under sponsorship of the U.S. Department of Labor/Employment and Training Administration (USDOL/ETA).</p>
  <ul class="list-inline">
        <li><i class="fa fa-sun-o text-yellow"></i> Bright Outlook</li>
        <li><i class="fa fa-leaf text-green"></i> Green Occupation</li>
      </ul>';

}
