<?php
/**
 *  Create and customize a asu news block from a asu news feed
 */

//require_once __DIR__ . '/asu_news.forms.inc';
require_once __DIR__ . '/asu_news.callbacks.inc';
require_once __DIR__ . '/asu_news.blocks.inc';
require_once __DIR__ . '/asu_news.helpers.inc';

/**
  * Implementation of hook_ctools_plugin_api().
  */
function asu_news_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function asu_news_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
* Implements hook_menu().
*/
function asu_news_menu() {

  $items['news/autocomplete'] = array(
    'title' => t('News AutoComp Menu'),
    'page callback' => 'select_all_asu_news',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* Implements hook_entity_info_alter().
*/
function asu_news_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['news_small_teaser'] = array(
    'label' => t('News Small Teaser'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['news_medium_teaser'] = array(
     'label' => t('News Medium Teaser'),
     'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['news_featured_teaser'] = array(
    'label' => t('News Featured Teaser'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['news_list_page_teaser'] = array(
    'label' => t('News List Page Teaser'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['news_list_page_featured_teaser'] = array(
    'label' => t('News List Page Featured Teaser'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['news_list_page_compact_teaser'] = array(
    'label' => t('News List Page Compact Teaser'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_image_default_styles().
*/
function asu_news_image_default_styles() {
  $styles = array();

  $styles['asunews_featured_teaser'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'height' => 320,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
      array(
        'name' => 'image_crop',
        'data' => array(
          'width' => 320,
          'height' => 320,
          'anchor' => 'left-top',
        ),
        'weight' => 1,
      ),
    ),
  );

  $styles['asunews_listing_featured_teaser'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 553,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
      array(
        'name' => 'image_crop',
        'data' => array(
          'width' => 553,
          'height' => 311,
          'anchor' => 'left-top',
        ),
        'weight' => 1,
      ),
    ),
  );

  $styles['asu_news_profile_image'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => 116,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
      array(
        'name' => 'image_crop',
        'data' => array(
          'width' => 116,
          'height' => 116,
        ),
        'weight' => 1,
      ),
    ),
  );

  $styles['asunews_thumbnail'] = array(
    'name' => 'asunews_thumbnail',
    'label' => 'asunews_thumbnail',
    'effects' => array(
      3 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 360,
          'height' => 200,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/**
* Implements hook_theme().
*/
function asu_news_theme(){
  $path = drupal_get_path('module', 'asu_news') . '/theme/templates';
  return array(
    'node__asu_news__full' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--full',
      'path' => $path,
    ),
    'node__asu_news__news_small_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-small-teaser',
      'path' => $path,
    ),
    'node__asu_news__news_medium_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-medium-teaser',
      'path' => $path,
    ),
    'node__asu_news__news_featured_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-featured-teaser',
      'path' => $path,
    ),
    'node__asu_news__news_list_page_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-list-page-teaser',
      'path' => $path,
    ),
    'node__asu_news__news_list_page_featured_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-list-page-featured-teaser',
      'path' => $path,
    ),
    'node__asu_news__news_list_page_compact_teaser' => array(
      'base hook' => 'node',
      'template' => 'node--asu-news--news-list-page-compact-teaser',
      'path' => $path,
    ),
    'asu_news_full_block' => array(
      'variables' => array('featured' => NULL, 'news_items' => NULL),
      'template' => 'asu-news-full-block',
      'path' => $path,
    ),
    'asu_news_highlighted_block' => array(
      'variables' => array('news_items' => NULL),
      'template' => 'asu-news-highlighted-block',
      'path' => $path,
    ),
    'asu_news_news_list_page' => array(
      'render element' => 'page',
      'variables' => array('vars' => NULL),
      'template' => 'asu-news-news-list-page',
      'path' => $path,
    ),
    'asu_news_field_body' => array(
      'render element' => 'page',
      'variables' => array('vars' => NULL),
      'template' => 'asu-news-field-body',
      'path' => $path,
    ),
    // to deal with default image
    'asu_news_image_style_outside_files' => array(
	    'variables' => array(
	      'style_name' => NULL,
	      'path' => NULL,
	      'alt' => '',
	      'title' => NULL,
	      'attributes' => array(),
	    ),
	  ),
    'page__asu_news' => array(
      'render element' => 'page',
      'base_hook' => 'page',
      'variables' => array('vars' => NULL),
      'template' => 'page--asu-news',
      'path' => $path,
    ),
  );
}

/**
  * This theme function is designed to deal with the limitation that
  * theme_image_style does not work with images outside the files directory.
  *
  * Usage is the same as theme_image_style.
  *
  * @param $variables
  */
function theme_asu_news_image_style_outside_files($variables) {
 $styled_path = image_style_path($variables['style_name'], $variables['path']);
 if (!file_exists($styled_path)) {
   $style = image_style_load($variables['style_name']);
   image_style_create_derivative($style, $variables['path'], $styled_path);
 }
 $variables['path'] = $styled_path;
 return theme('image', $variables);
}

function asu_news_process_html(&$vars) {
 if (arg(0) == 'news') {
   $vars['head_title'] = implode(' | ', $vars['head_title_array']);
 }
}

/**
* Implements hook_preprocess_page().
*/
function asu_news_preprocess_page (&$vars) {
  // ASU news listing page

  if (arg(0) == 'news') {
    drupal_add_css(drupal_get_path('module', 'asu_news') . '/theme/css/asumod.css', array('group' => CSS_THEME, 'every_page' => TRUE));
    drupal_set_title('News');
    $vars['title'] = 'News';
    global $pager_total;

    $pager_settings = array(
      'pager_total' => $pager_total,
    );

    drupal_add_js(array('asu_news' => $pager_settings), 'setting');
  }

  if (!empty($vars['node']) && $vars['node']->type == 'asu_news') {
    drupal_add_css(drupal_get_path('module', 'asu_news') . '/theme/css/asumod.css', array('group' => CSS_THEME, 'every_page' => TRUE));

    drupal_add_js(drupal_get_path('module', 'asu_news') . '/theme/js/clipboard.min.js', array('type' => 'file', 'scope' => 'header', 'weight' => 5));

    drupal_add_css(drupal_get_path('module', 'asu_news') . '/theme/js/selection-sharer/dist/selection-sharer.css', array('group' => CSS_THEME, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'asu_news') . '/theme/js/selection-sharer/dist/selection-sharer.js', array('type' => 'file', 'scope' => 'footer', 'weight' => 5));
    drupal_add_js(drupal_get_path('module', 'asu_news') . '/theme/js/asu_news.js', array('type' => 'file', 'scope' => 'footer', 'weight' => 6));

    if (!empty($vars['page'])) {
      $vars['theme_hook_suggestions'][] = 'page__asu_news';
    }

    $breadcrumbs = block_load('easy_breadcrumb', 'easy_breadcrumb');
    $bc_render_array = _block_get_renderable_array(_block_render_blocks(array($breadcrumbs)));
    $bc_render_array['easy_breadcrumb_easy_breadcrumb']['easy_breadcrumb']['#prefix'] = '<div class="column container">';
    $bc_render_array['easy_breadcrumb_easy_breadcrumb']['easy_breadcrumb']['#suffix'] = '</div>';

    $vars['breadcrumbs'] = $bc_render_array;
  }
}

function asu_news_preprocess_node(&$vars) {
  if ($vars['node']->type == 'asu_news') {
    switch ($vars['view_mode']) {
      case 'news_small_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_small_teaser';
        $vars['classes_array'][] = 'news-small-teaser';
        $content = $vars['content'];

        $content['asunews_image'] = _asu_news_get_image('asunews_thumbnail', $vars['node']);

        $vars['content'] = $content;
        break;
      case 'news_medium_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_medium_teaser';
        $vars['classes_array'][] = 'news-medium-teaser';
        $content = $vars['content'];

        $content['asunews_image'] = _asu_news_get_image('asunews_thumbnail', $vars['node']);

        $saf_tag = field_get_items('node', $vars['node'], 'field_saf');
        $content['saf_tag'] = '';
        if (!empty($saf_tag[0])) {
          $saf_term = taxonomy_term_load($saf_tag[0]['tid']);
          $content['saf_tag'] = $saf_term->name;
        }

        $vars['content'] = $content;
        break;
      case 'news_featured_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_featured_teaser';
        $vars['classes_array'][] = 'news-featured-teaser';
        $content = $vars['content'];

        $content['asunews_image'] = _asu_news_get_image('asunews_featured_teaser', $vars['node']);

        $body = field_view_field('node', $vars['node'], 'body', array(
          'label'=>'hidden',
          'type' => 'text_trimmed',
          'settings'=> array('trim_length' => 360),
        ));

        $teaser = field_view_field('node', $vars['node'], 'field_asunews_teaser', array(
          'label'=>'hidden',
          'type' => 'text_trimmed',
          'settings'=> array('trim_length' => 280),
        ));

        if(!empty($teaser)) {
          $content['asunews_body'] = $teaser;
        }
        else {
          $content['asunews_body'] = $body;
        }


        $saf_tag = field_get_items('node', $vars['node'], 'field_saf');
        $content['saf_tag'] = field_view_value('node', $vars['node'], 'field_saf', $saf_tag[0], array(
          'label'=>'hidden',
          'type' => 'taxonomy_term_reference_plain',
        ));

        $vars['classes_array'][] = 'news-featured-teaser';

        $vars['content'] = $content;
        break;
      case 'news_list_page_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_list_page_teaser';
        $vars['classes_array'][] = 'news-list-page-teaser';
        $content = $vars['content'];

        $content['asunews_image'] = _asu_news_get_image('asunews_thumbnail', $vars['node']);

        $body = field_view_field('node', $vars['node'], 'body', array(
          'label'=>'hidden',
          'type' => 'text_summary_or_trimmed',
          'settings'=> array('trim_length' => 240),
        ));

        $teaser = field_view_field('node', $vars['node'], 'field_asunews_teaser', array(
          'label'=>'hidden',
          'type' => 'plain_text',
          'settings'=> array('trim_length' => 360),
        ));

        if(!empty($teaser)) {
          $content['asunews_body'] = $teaser;
        }
        else {
          $content['asunews_body'] = $body;
        }

        $vars['content'] = $content;
        break;
      case 'news_list_page_featured_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_list_page_featured_teaser';
        $vars['classes_array'][] = 'news-list-page-featured-teaser';
        $content = $vars['content'];

        $vars['date'] = format_date($vars['changed'], 'custom', 'M. d, Y');

        $content['asunews_image'] = _asu_news_get_image('asunews_listing_featured_teaser', $vars['node']);

        $body = field_view_field('node', $vars['node'], 'body', array(
          'label'=>'hidden',
          'type' => 'text_summary_or_trimmed',
          'settings'=> array('trim_length' => 600),
        ));
        $teaser = field_view_field('node', $vars['node'], 'field_asunews_teaser', array(
          'label'=>'hidden',
          'type' => 'plain_text',
          'settings'=> array('trim_length' => 360),
        ));

        if(!empty($teaser)) {
          $content['asunews_body'] = $teaser;
        }
        else {
          $content['asunews_body'] = $body;
        }

        $vars['content'] = $content;
        break;
      case 'news_list_page_compact_teaser':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__news_list_page_compact_teaser';
        $vars['classes_array'][] = 'news-list-page-compact-teaser';
        $content = $vars['content'];

        $body = field_view_field('node', $vars['node'], 'body', array(
          'label'=>'hidden',
          'type' => 'text_summary_or_trimmed',
          'settings'=> array('trim_length' => 240),
        ));
        $teaser = field_view_field('node', $vars['node'], 'field_asunews_teaser', array(
          'label'=>'hidden',
          'type' => 'plain_text',
          'settings'=> array('trim_length' => 360),
        ));

        if(!empty($teaser)) {
          $content['asunews_body'] = $teaser;
        }
        else {
          $content['asunews_body'] = $body;
        }

        $vars['content'] = $content;
        break;
      case 'full':
        $vars['theme_hook_suggestions'][] = 'node__asu_news__full';
        $content = $vars['content'];

        foreach ($content as $key=>$element) {
          $element['#label_display'] = 'hidden';
          $content[$key] = $element;
        }

        // @TODO - ASU Social Share - reuse?
        // $content['share'] = field_view_field('node', $vars['node'], 'field_asu_social_share', array(
        //   'label'=>'hidden',
        //   'type' => 'gigya_sharebar',
        // ));

        $vars['content'] = $content;

        $vars = _asu_news_set_full_view_vars($vars);

        break;
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function asu_news_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == 'asu_news_asu_news_block_edit_form' || $form_id == 'asu_news_asu_news_listing_edit_form') {
    unset($form['override_title']);
    unset($form['override_title_text']);
    unset($form['override_title_markup']);
  }
}

/**
* Implements hook_element_info_alter().
*
* Sets the text format processor to a custom callback function.
* This code is taken from the Better Formats module.
*/
function asu_news_format_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    foreach ($type['text_format']['#process'] as &$callback) {
      if ($callback === 'filter_process_format') {
        $callback = 'asu_news_format_filter_process_format';
      }
    }
  }
}

/**
* Callback for MODULENAME_element_info_alter().
*/
function asu_news_format_filter_process_format($element) {
  $element = filter_process_format($element);
  // Change input format to "Filtered HTML" for body fields of article nodes
  if ($element['#bundle'] == 'asu_news' && $element['#field_name'] == 'body') {
    $element['format']['format']['#default_value'] = 'panopoly_wysiwyg_text';
  }
  return $element;
}
