<?php

/**
 * Implements hook_block_info().
 */
function webspark_warranty_block_info()
{
  $blocks['warranty_status'] = array(
    'info'  =>  t('Warranty Status')
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function webspark_warranty_block_view($delta = '')
{
  $currentStatus = checkWarrantyStatus();

  switch ($delta)
  {
    case 'warranty_status':
      $block['subject'] = t('Subject of Webspark Warranty:');
      $block['content'] = t($currentStatus);

      break;
  }

  return $block;
}

function checkWarrantyStatus()
{
  $systemTableValue = db_select('system', 's')
                                ->fields('s')
                                ->execute()
                                ->fetchAll();

  $json = file_get_contents("contrib/standardModuleList.json", true);
  $moduleList = json_decode($json, true);

//  print_r($moduleList);
//  print_r($systemTableValue[0]->name);

  $status = false;

  return $status ? 'True' : 'False';
}
