<?php

/**
 * Implements hook_block_info().
 */
function webspark_warranty_block_info()
{
  $blocks['warranty_status'] = array(
    'info'  =>  t('Warranty Status')
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function webspark_warranty_block_view($delta = '')
{
  $currentStatus = checkWarrantyStatus();

  switch ($delta)
  {
    case 'warranty_status':
      $block['subject'] = t('Subject of Webspark Warranty:');
      $block['content'] = t($currentStatus);

      break;
  }

  return $block;
}

/**
 * getAllInstalledModules() - Uses Drupal's Database API to get all of the modules
 *                            currently installed on the site (which resides within
 *                            the {system} table)
 *
 * @return $allModulesArr - All installed modules in an associative array
 */
function getAllInstalledModules()
{
  // All installed modules output as a flat array with Standard Class Objects
  $allModulesStd = db_select('system', 's')
                    ->fields('s', array('name'))
                    ->condition('status', '1')
                    ->execute()
                    ->fetchAll();

  // Converts from Standard Class Objects to an associative array
  $allModulesArr = json_decode(json_encode($allModulesStd), true);

  return $allModulesArr;
}

/**
 * getModulesWithinWarranty() - Imports all warranty-covered module names listed
 *                              within a JSON file and puts them all into one PHP
 *                              associative array
 *
 * @return $warrantyModulesArr - All modules covered under Webspark's warranty
 *                               in an associative array
 */
function getModulesWithinWarranty()
{
  $warrantyModulesJSON = file_get_contents("contrib/standardModuleList.json", true);
  $warrantyModulesArr = json_decode($warrantyModulesJSON, true);

  return $warrantyModulesArr;
}

function checkWarrantyStatus()
{
  $status = true;

  $installedModules = getAllInstalledModules();
  $supportedModules = getModulesWithinWarranty();

  if (sizeof(array_diff_assoc($installedModules, $supportedModules)) > 0)
    $status = false;

  return $status ? 'True' : 'False';
}
