<?php
/**
 * @file
 * asu_isearch.features.uuid_fpp.inc
 */

/**
 * Implements hook_uuid_features_default_fpps().
 */
function asu_isearch_uuid_features_default_fpps() {
  $fpps = array();

  $fpps[] = array(
    'timestamp' => 1449595916,
    'title' => 'Teaching',
    'log' => '',
    'bundle' => 'panel_tabs_extended_tab',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Teaching',
    'admin_description' => '',
    'category' => 'Tab panes',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1445366376,
    'uuid' => '2ffb11d5-0954-4090-a05e-d21f61573d13',
    'language' => '',
  );
  $fpps[] = array(
    'timestamp' => 1449595886,
    'title' => 'Bio',
    'log' => '',
    'bundle' => 'panel_tabs_extended_tab',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Bio',
    'admin_description' => '',
    'category' => 'Tab panes',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1445363843,
    'uuid' => '61e05864-8ba7-4858-b9ca-3b9b078b4ca3',
    'language' => 'und',
  );
  $fpps[] = array(
    'timestamp' => 1477426920,
    'title' => 'Industry Experience',
    'log' => '',
    'bundle' => 'panel_tabs_extended_tab',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Industry Experience',
    'admin_description' => '',
    'category' => 'Tab Panes',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1477426784,
    'uuid' => '76ebd555-a0f4-4e91-bc2c-fe5c9ba1502c',
    'language' => 'und',
  );
  $fpps[] = array(
    'timestamp' => 1449595909,
    'title' => 'Research',
    'log' => '',
    'bundle' => 'panel_tabs_extended_tab',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Research',
    'admin_description' => '',
    'category' => 'Tab panes',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1445363279,
    'uuid' => 'b3ac9a14-7900-413f-9c00-336674af69a5',
    'language' => '',
  );
  $fpps[] = array(
    'timestamp' => 1449595902,
    'title' => 'Public Work',
    'log' => '',
    'bundle' => 'panel_tabs_extended_tab',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Public Work',
    'admin_description' => '',
    'category' => 'Tab panes',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1445366392,
    'uuid' => 'e1993e63-c13a-4429-9787-9948ee480191',
    'language' => '',
  );
  return $fpps;
}
