<?php
/**
 * @file
 * webspark_wysiwyg.features.features_overrides.inc
 */

/**
 * Implements hook_features_override_default_overrides().
 */
function webspark_wysiwyg_features_override_default_overrides() {
  // This code is only used for UI in features. Exported alters hooks do the magic.
  $overrides = array();

  // Exported overrides for: filter
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|0"] = 'a*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|10"] = 'f*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|100"] = 'Y*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|102"] = 'Z*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|12"] = 'g*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|14"] = 'h*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|16"] = 'i*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|18"] = 'j*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|2"] = 'b*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|20"] = 'k*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|22"] = 'l*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|24"] = 'm*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|26"] = 'n*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|28"] = 'o*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|30"] = 'p*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|32"] = 'q*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|34"] = 'r*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|36"] = 's*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|38"] = 't*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|4"] = 'c*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|40"] = 'u*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|42"] = 'v*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|44"] = 'w*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|46"] = 'x*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|48"] = 'y*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|50"] = 'z*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|52"] = 'A*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|54"] = 'B*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|56"] = 'C*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|58"] = 'D*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|6"] = 'd*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|60"] = 'E*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|62"] = 'F*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|64"] = 'G*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|66"] = 'H*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|68"] = 'I*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|70"] = 'J*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|72"] = 'K*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|74"] = 'L*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|76"] = 'M*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|78"] = 'N*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|8"] = 'e*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|80"] = 'O*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|82"] = 'P*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|84"] = 'Q*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|86"] = 'R*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|88"] = 'S*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|90"] = 'T*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|92"] = 'U*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|94"] = 'V*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|96"] = 'W*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|rule_valid_ids|98"] = 'X*';
  $overrides["filter.panopoly_wysiwyg_text.filters|wysiwyg|settings|valid_elements"] = 'a[href|target<_blank|title|style|class|id],
  div[style|class|align<center?justify?left?right],
  br,em,i,strong,cite,code,blockquote,ul,ol,li,dl,dt,dd,
  table[style|class],thead,th,tbody,tr,td,
  span[style],p[style|class],
  h1[style|class],h2[style|class],h3[style|class],h4[style|class],h5[style|class],h6[style|class],
  img[!src|title|alt|style|width|height|class|hspace|vspace],
  @[style|class],#p,&nbsp;
  buttton[style|class]';

  // Exported overrides for: image
  $overrides["image.wysiwyg_template_thumbnail.label"] = 'wysiwyg_template_thumbnail';

  // Exported overrides for: wysiwyg
  $overrides["wysiwyg.panopoly_html_text.settings|block_formats"] = 'p,h2,h3,h4,h5,h6';
  $overrides["wysiwyg.panopoly_html_text.settings|buttons|default|link"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_html_text.settings|buttons|default|stroke"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_html_text.settings|buttons|linkit"] = array(
    'linkit' => 1,
  );
  $overrides["wysiwyg.panopoly_html_text.settings|show_toggle"] = 1;
  $overrides["wysiwyg.panopoly_html_text.settings|user_choose"] = 1;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|block_formats"] = 'p,h2,h3,h4,h5,h6';
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|default|anchor"] = 1;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|default|forecolor"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|default|hr"] = 1;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|default|styleselect"] = 1;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|default|underline"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|paste|pastetext"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|pdw"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|spellchecker"]["DELETED"] = TRUE;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|table"] = array(
    'tablecontrols' => 1,
  );
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|buttons|template"] = array(
    'template' => 1,
  );
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|css_classes"] = 'Image align left=pull-left
      Image align right=pull-right
      Oval image=img-circle
      Image with rounded corners=img-rounded
      Image with double-border=img-thumbnail
      Primary button=btn btn-primary
      Primary button large=btn btn-primary btn-lg
      Primary button full-col-wide=btn btn-primary btn-block
      Primary button large col-wide=btn btn-primary btn-lg btn-block
      Secondary button=btn btn-secondary
      Secondary button large=btn btn-secondary btn-lg
      Secondary button full-col-wide=btn btn-secondary btn-block
      Secondary button large col-wide=btn btn-secondary btn-lg btn-block
      RFI/Visit/Apply (RVA) button=btn btn-gold
      RVA button large=btn btn-gold btn-lg
      RVA button full-col-wide=btn btn-gold btn-block
      RVA button large col-wide=btn btn-gold btn-lg btn-block
      Explore Our Programs (EOP) button=btn btn-blue
      EOP button large=btn btn-blue btn-lg
      EOP button full-col-wide=btn btn-blue btn-block
      EOP button large col-wide=btn btn-blue btn-lg btn-block';
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|css_path"] = '%b%t/css/innovation-main.css,%b%t/css/grid.css,%b%t/css/buttons.css,%b%t/css/forms.css,%b%t/css/nav.css,%b%t/fonts/roboto/css/roboto.css';
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|css_setting"] = 'self';
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|show_toggle"] = 1;
  $overrides["wysiwyg.panopoly_wysiwyg_text.settings|user_choose"] = 1;

 return $overrides;
}
