<?php
/**
 * @file
 * Alters the payment method selection dynamically, based on what event is selected.
 */

/**
 * Implements hook_commerce_payment_method_info_alter()
 */
function ace_commerce_commerce_payment_method_info_alter(&$payment_methods) {
  // Improve the display title of the Cybersource
  if (isset($payment_methods['cybersource_sawm']['display_title'])) {
    $payment_methods['cybersource_sawm']['display_title'] = '<div id="cybersource-cards">Credit Card via CyberSource</div>';
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function ace_commerce_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  $form['#validate'][] = '_ace_commerce_cart_add_to_cart_form_validate';
}
/**
 * Helper function - Checks to see if there's a product already in the cart with
 * a different payment method. If so, the product cannot be added.
 */
function _ace_commerce_cart_add_to_cart_form_validate($form, &$form_state) {
  // Get cart from user ID and get payment method of current item
  $order = commerce_cart_order_load($form_state['values']['uid']);

  // #1 Get new product and its type - Is new product of product type?
  $new_product = commerce_product_load($form_state['values']['product_id']);
  $new_product_type = array(
    $new_product->type => $new_product->type,
  );
  $item_is_cyber = rules_invoke_component('rules_is_cyber_product', $new_product, $new_product_type);

  // #2 Get product types for all items in cart and compare with rules_are_products_of_type
  $cart_has_cyber = FALSE;
  $cart_cyber_items = array();
  $wrapper = entity_metadata_wrapper('commerce_order', $order);
  foreach ($wrapper->commerce_line_items as $delta => $line_item_wrapper) {
    if (rules_invoke_component('rules_are_products_of_type', $order)) {
      $cart_has_cyber = TRUE;
      $cart_cyber_items[] = $line_item_wrapper->commerce_product->value()->title;
    }
  }
  // Either all cart items and the new item should both be cyber (i.e. both TRUE)
  // or not (both FALSE). If they don't match, stop the adding of the new item.
  if ($cart_has_cyber !== $item_is_cyber) {
    $payment_method = ($item_is_cyber) ? "CyberSource" : "Quikpay";
    $variables = array(
      'items' => $cart_cyber_items,
      'title' => NULL,
      'type' => 'ul',
      'attributes' => array(),
    );
    $items = theme_item_list($variables);
    form_set_error('payment_methods_error', "<strong>Error - Can't add " . $new_product->title
      . " to your cart!</strong><br>
    The following item - " . $new_product->title . " - 
    cannot be added to your cart at this time because it needs to be purchased 
    using a payment method (" . $payment_method . ") that cannot be used with the 
    following items already in your cart: <br><br>
    " . $items . "To resolve this issue, either complete your purchase for the above items 
    in <a href='/cart'>your cart</a> or remove all of the above items, and then 
    return to this page and try to add the " . $new_product->title . " to your cart 
    again.
    <br><br>We're sorry for any inconvenience this may cause.");
  }
  else {
    // They are the same. All is well.
  }
}
