<?php
/**
 * @file
 * Code for the Webspark News and Events (Step 2) feature.
 */

include_once 'webspark_newsevents.features.inc';

function webspark_newsevents_init() {
  drupal_add_css(drupal_get_path('module', 'webspark_newsevents') . '/css/webspark_newsevents.css', array('weight' => 99, 'group' => CSS_DEFAULT));
  drupal_add_js(drupal_get_path('module', 'webspark_newsevents') . '/js/webspark_newsevents.js', array('scope' => 'footer', 'group' => JS_THEME, 'weight' => 95));
}

/**
 * Implements hook_field_default_field_instances_alter().
 *
 * Set the default image.
 */
function webspark_newsevents_field_default_field_instances_alter(&$fields) {
  if (isset($fields['node-asu_news-field_asunews_image']['settings']['default_image'])) {
    $fields['node-asu_news-field_asunews_image']['settings']['default_image'] = variable_get('webspark_newsevents_asunews_image_fid');
  }
}